import type {
  ApprovalRecord,
  DemandLine,
  RoleInboxItem,
  StockMovement,
  WorkflowDocument,
  WorkflowLane,
} from './types';

export const workflowLanes: WorkflowLane[] = [
  {
    id: 'coordination',
    label: 'Điều phối',
    owner: 'Điều phối ca',
    stage: 'Chốt đơn',
    status: 'Đã chốt đơn',
    nextAction: 'Gửi tính định lượng',
    waiting: 1,
    blocked: 0,
    done: 4,
    tone: 'success',
    route: '/meal-orders',
  },
  {
    id: 'planning',
    label: 'KHSX',
    owner: 'Kế hoạch định lượng',
    stage: 'Kiểm tồn kho',
    status: 'Thiếu nguyên liệu',
    nextAction: 'Đề xuất mua thêm',
    waiting: 2,
    blocked: 1,
    done: 3,
    tone: 'warning',
    route: '/weekly-menu',
  },
  {
    id: 'management',
    label: 'Quản lí',
    owner: 'Quản lí vận hành',
    stage: 'Duyệt mua / duyệt xuất',
    status: 'Chờ duyệt',
    nextAction: 'Duyệt danh sách mua thêm',
    waiting: 3,
    blocked: 1,
    done: 2,
    tone: 'warning',
    route: '/approvals',
  },
  {
    id: 'purchasing',
    label: 'Thu mua',
    owner: 'Nhân sự thu mua',
    stage: 'Thu mua',
    status: 'Chờ chọn nhà cung cấp',
    nextAction: 'Chọn nhà cung cấp',
    waiting: 2,
    blocked: 1,
    done: 1,
    tone: 'danger',
    route: '/purchasing',
  },
  {
    id: 'warehouse',
    label: 'Thủ kho',
    owner: 'Kho nguyên liệu',
    stage: 'Xuất kho',
    status: 'Chờ xuất kho',
    nextAction: 'Tạo phiếu xuất kho',
    waiting: 4,
    blocked: 1,
    done: 5,
    tone: 'warning',
    route: '/warehouse',
  },
  {
    id: 'kitchen',
    label: 'Bếp trưởng',
    owner: 'Bếp trưởng ca trưa',
    stage: 'Bếp nhận',
    status: 'Chờ nhận nguyên liệu',
    nextAction: 'Xác nhận nhận nguyên liệu',
    waiting: 2,
    blocked: 1,
    done: 2,
    tone: 'warning',
    route: '/chef-dashboard',
  },
  {
    id: 'admin',
    label: 'Admin',
    owner: 'Quản trị dữ liệu',
    stage: 'Điều chỉnh / thông báo',
    status: 'Chờ kiểm tra',
    nextAction: 'Điều chỉnh BOM',
    waiting: 2,
    blocked: 0,
    done: 1,
    tone: 'neutral',
    route: '/admin-data',
  },
];

export const roleInboxItems: RoleInboxItem[] = [
  {
    id: 'inbox-purchase-approval',
    laneId: 'management',
    owner: 'Quản lí vận hành',
    title: 'Danh sách mua thêm cho ca trưa',
    description: 'Thiếu 18 kg cá basa và 12 kg cải thìa sau kiểm tồn kho.',
    due: 'Trước 09:20',
    nextAction: 'Duyệt danh sách mua thêm',
    tone: 'warning',
    route: '/approvals',
  },
  {
    id: 'inbox-issue-approval',
    laneId: 'management',
    owner: 'Quản lí vận hành',
    title: 'Nhu cầu xuất kho KHSX-0613-TRUA',
    description: 'Phiếu xuất cần duyệt trước khi kho soạn hàng cho bếp.',
    due: 'Trước 09:35',
    nextAction: 'Duyệt nhu cầu xuất',
    tone: 'warning',
    route: '/approvals',
  },
  {
    id: 'inbox-price-variance',
    laneId: 'purchasing',
    owner: 'Thu mua',
    title: 'Giá hành lá vượt ngưỡng 15%',
    description: 'Báo giá mới tăng 18% so với lần nhập gần nhất.',
    due: 'Trước khi đặt hàng',
    nextAction: 'Gửi cảnh báo biến động giá',
    tone: 'danger',
    route: '/purchasing',
  },
  {
    id: 'inbox-warehouse-shortage',
    laneId: 'warehouse',
    owner: 'Thủ kho',
    title: 'Không đủ hàng cho phiếu xuất bếp',
    description: 'Kho còn thiếu 4 kg gừng, cần tạo nhánh mua thêm hoặc xuất bổ sung.',
    due: 'Trước 10:10',
    nextAction: 'Tạo danh sách mua thêm',
    tone: 'danger',
    route: '/warehouse',
  },
  {
    id: 'inbox-kitchen-receiving',
    laneId: 'kitchen',
    owner: 'Bếp trưởng',
    title: 'Chờ xác nhận nhận nguyên liệu',
    description: 'Phiếu XK-0613-TRUA đã xuất nhưng bếp chưa ký nhận đủ.',
    due: 'Trước 10:30',
    nextAction: 'Xác nhận nhận nguyên liệu',
    tone: 'warning',
    route: '/chef-dashboard',
  },
  {
    id: 'inbox-admin-bom',
    laneId: 'admin',
    owner: 'Admin dữ liệu',
    title: 'Điều chỉnh BOM món cá kho',
    description: 'Bếp đề xuất giảm đường và tăng nước mắm cho định lượng chuẩn.',
    due: 'Sau ca trưa',
    nextAction: 'Điều chỉnh BOM',
    tone: 'neutral',
    route: '/admin-data',
  },
];

export const approvalRecords: ApprovalRecord[] = [
  {
    id: 'APR-MUA-0613-01',
    type: 'purchase',
    title: 'Duyệt danh sách mua thêm',
    source: 'KHSX-0613-TRUA',
    owner: 'Quản lí vận hành',
    submittedBy: 'KHSX',
    deadline: '09:20',
    status: 'Chờ duyệt',
    reason: 'Không đủ nguyên liệu để xuất theo danh sách.',
    nextAction: 'Duyệt danh sách mua thêm',
    tone: 'warning',
    materials: [
      { name: 'Cá basa', quantity: 18, unit: 'kg' },
      { name: 'Cải thìa', quantity: 12, unit: 'kg' },
    ],
  },
  {
    id: 'APR-XUAT-0613-02',
    type: 'issue',
    title: 'Duyệt nhu cầu xuất kho',
    source: 'Đơn ca trưa đã chốt',
    owner: 'Quản lí vận hành',
    submittedBy: 'Điều phối ca',
    deadline: '09:35',
    status: 'Cần bổ sung thông tin',
    reason: 'Dòng thịt heo chưa khớp định lượng sau điều chỉnh số suất.',
    nextAction: 'Trả lại để bổ sung',
    tone: 'danger',
    materials: [
      { name: 'Thịt heo nạc', quantity: 36, unit: 'kg' },
      { name: 'Gạo thơm', quantity: 90, unit: 'kg' },
    ],
  },
  {
    id: 'APR-ADJ-0613-03',
    type: 'adjustment',
    title: 'Duyệt điều chỉnh tồn',
    source: 'Kiểm kê nhanh kho mát',
    owner: 'Quản lí vận hành',
    submittedBy: 'Thủ kho',
    deadline: 'Sau ca trưa',
    status: 'Đã duyệt',
    reason: 'Lệch tồn hành lá sau nhập bù đã có biên bản.',
    nextAction: 'Ghi nhận điều chỉnh tồn',
    tone: 'success',
    materials: [{ name: 'Hành lá', quantity: 3, unit: 'kg' }],
  },
];

export const demandLines: DemandLine[] = [
  {
    id: 'DEM-CA-BASA',
    material: 'Cá basa',
    required: 42,
    available: 24,
    reserved: 4,
    unit: 'kg',
    source: 'Cá kho tiêu',
    status: 'Thiếu nguyên liệu',
    nextAction: 'Đề xuất mua thêm',
    tone: 'danger',
  },
  {
    id: 'DEM-GAO',
    material: 'Gạo thơm',
    required: 90,
    available: 120,
    reserved: 12,
    unit: 'kg',
    source: 'Cơm trắng',
    status: 'Tồn kho đủ',
    nextAction: 'Sinh nhu cầu xuất',
    tone: 'success',
  },
  {
    id: 'DEM-CAI-THIA',
    material: 'Cải thìa',
    required: 30,
    available: 18,
    reserved: 2,
    unit: 'kg',
    source: 'Rau xào tỏi',
    status: 'Thiếu nguyên liệu',
    nextAction: 'Đề xuất mua thêm',
    tone: 'danger',
  },
  {
    id: 'DEM-HANH',
    material: 'Hành lá',
    required: 8,
    available: 9,
    reserved: 1,
    unit: 'kg',
    source: 'Canh bí đỏ',
    status: 'Tồn kho đủ',
    nextAction: 'Tạo phiếu xuất kho',
    tone: 'success',
  },
];

export const workflowDocuments: WorkflowDocument[] = [
  {
    id: 'KHSX-0613-TRUA',
    type: 'KHSX',
    title: 'Kế hoạch sản xuất ca trưa',
    status: 'Đã sinh KHSX',
    owner: 'KHSX',
    summary: '540 suất, 4 món, chờ kho xuất cho bếp.',
    route: '/weekly-menu',
    tone: 'success',
    lines: [
      { label: 'Menu', value: 'Cá kho tiêu, rau xào, canh bí đỏ' },
      { label: 'Số suất', value: '540' },
      { label: 'Bàn giao bếp', value: '10:30', tone: 'warning' },
    ],
  },
  {
    id: 'MUA-0613-01',
    type: 'Danh sách mua thêm',
    title: 'Mua thêm sau kiểm tồn',
    status: 'Chờ duyệt',
    owner: 'Quản lí vận hành',
    summary: 'Cần duyệt trước khi thu mua chọn nhà cung cấp.',
    route: '/approvals',
    tone: 'warning',
    lines: [
      { label: 'Cá basa', value: '18 kg thiếu', tone: 'danger' },
      { label: 'Cải thìa', value: '12 kg thiếu', tone: 'danger' },
    ],
  },
  {
    id: 'PO-0613-02',
    type: 'Đơn mua',
    title: 'Đặt nguyên liệu ca trưa',
    status: 'Chờ chọn nhà cung cấp',
    owner: 'Thu mua',
    summary: 'Báo giá hành lá vượt ngưỡng 15%, cần cảnh báo.',
    route: '/purchasing',
    tone: 'danger',
    lines: [
      { label: 'Nhà cung cấp đề xuất', value: 'Thực phẩm Minh An' },
      { label: 'Biến động giá', value: '+18%', tone: 'danger' },
    ],
  },
  {
    id: 'PN-0613-01',
    type: 'Phiếu nhập',
    title: 'Nhập kho hàng mua bổ sung',
    status: 'Chờ nhập kho',
    owner: 'Thủ kho',
    summary: 'Chờ thu mua chuyển hàng tới kho mát.',
    route: '/warehouse',
    tone: 'warning',
    lines: [
      { label: 'Điểm nhận', value: 'Kho mát' },
      { label: 'Hạn xử lí', value: '10:00' },
    ],
  },
  {
    id: 'PX-0613-TRUA',
    type: 'Phiếu xuất',
    title: 'Xuất kho cho bếp',
    status: 'Chờ xuất kho',
    owner: 'Thủ kho',
    summary: 'Theo nhu cầu xuất đã duyệt, bếp nhận trước 10:30.',
    route: '/warehouse',
    tone: 'warning',
    lines: [
      { label: 'KHSX', value: 'KHSX-0613-TRUA' },
      { label: 'Bếp nhận', value: '10:30', tone: 'warning' },
    ],
  },
  {
    id: 'PT-0613-01',
    type: 'Phiếu trả',
    title: 'Trả nguyên liệu dư sau nấu',
    status: 'Có nguyên liệu dư',
    owner: 'Bếp trưởng',
    summary: 'Bếp còn rau và gia vị cần ghi nhận trả kho.',
    route: '/chef-dashboard',
    tone: 'warning',
    lines: [
      { label: 'Cải thìa', value: '2 kg dư' },
      { label: 'Nước mắm', value: '1 chai dư' },
    ],
  },
  {
    id: 'ADJ-BOM-0613',
    type: 'Điều chỉnh',
    title: 'Điều chỉnh BOM cá kho',
    status: 'Chờ kiểm tra',
    owner: 'Admin dữ liệu',
    summary: 'Cập nhật định lượng sau phản hồi bếp trưởng.',
    route: '/admin-data',
    tone: 'neutral',
    lines: [
      { label: 'Đường', value: 'Giảm 0.5 kg / 100 suất' },
      { label: 'Nước mắm', value: 'Tăng 0.3 l / 100 suất' },
    ],
  },
];

export const stockMovements: StockMovement[] = [
  {
    id: 'MOV-REC-01',
    type: 'receipt',
    documentNo: 'PN-0613-01',
    material: 'Cá basa',
    quantity: 18,
    unit: 'kg',
    owner: 'Thủ kho',
    status: 'Chờ nhập kho',
    nextAction: 'Nhập kho nguyên liệu',
    tone: 'warning',
  },
  {
    id: 'MOV-ISS-01',
    type: 'issue',
    documentNo: 'PX-0613-TRUA',
    material: 'Gạo thơm',
    quantity: 90,
    unit: 'kg',
    owner: 'Thủ kho',
    status: 'Chờ xuất kho',
    nextAction: 'Xuất kho cho bếp',
    tone: 'warning',
  },
  {
    id: 'MOV-SUP-01',
    type: 'supplemental',
    documentNo: 'PXBS-0613-01',
    material: 'Gừng',
    quantity: 4,
    unit: 'kg',
    owner: 'Thủ kho',
    status: 'Không đủ hàng',
    nextAction: 'Tạo danh sách mua thêm',
    tone: 'danger',
  },
  {
    id: 'MOV-RET-01',
    type: 'return',
    documentNo: 'PT-0613-01',
    material: 'Cải thìa',
    quantity: 2,
    unit: 'kg',
    owner: 'Bếp trưởng',
    status: 'Có nguyên liệu dư',
    nextAction: 'Trả nguyên liệu',
    tone: 'warning',
  },
  {
    id: 'MOV-ADJ-01',
    type: 'adjustment',
    documentNo: 'ADJ-STOCK-0613',
    material: 'Hành lá',
    quantity: 3,
    unit: 'kg',
    owner: 'Admin dữ liệu',
    status: 'Đã điều chỉnh tồn',
    nextAction: 'Gửi thông báo vận hành',
    tone: 'success',
  },
];
