import type { CatalogDish } from '@/api/dishCatalogApi'
import { useMenuCost } from '@/features/projects/weekly-menu/cost/useMenuCost'
import type { WeeklyMenuScope } from '@/features/projects/weekly-menu/schedule/types'
import type { WeeklyPlanRow } from '@/features/projects/weekly-menu/model/types'
import { formatCurrency, formatNumber, formatQuantity } from '@/lib/formatters'
import { EmptyState, InlineAlert } from '@/components/common'
export function CostScreen(props: { scope: WeeklyMenuScope; sourceLabel: string; weeklyPlanRows: WeeklyPlanRow[]; dishesById: Map<string, CatalogDish>; dishesByName: Map<string, CatalogDish> }) {
  const { presentation: p, actions } = useMenuCost(props)
  return <section aria-label="Giá vốn dự kiến theo ngày"><label>Ngày tính giá vốn<select value={p.activeDay?.key ?? ''} onChange={event => actions.selectDay(event.target.value)}>{p.dayPages.map(day => <option key={day.key} value={day.key}>{day.label} · {day.date}</option>)}</select></label>
    <div className="planning-read-summary"><span>Định mức: <strong>{formatCurrency(props.scope.menuPrice)}</strong></span><span>Giá vốn dự kiến ngày: <strong>{p.rows.length > 0 && p.rowsWithBom.length === 0 ? 'Chưa xác định' : formatCurrency(p.total)}</strong></span><span>Thiếu BOM: <strong>{p.rowsMissingBom.length} dòng</strong></span></div>
    <p className="mb-3 text-xs text-slate-500">{p.sourceLabel}. Giá vốn từ gross BOM × giá tham chiếu, không phải chi phí thực hiện.</p>
    {p.rowsMissingBom.length > 0 && <InlineAlert title="Giá vốn chưa đầy đủ" variant="warning">Dòng thiếu BOM không đóng góp vào tổng; không diễn giải là giá vốn bằng 0.</InlineAlert>}
    {p.rows.length === 0 ? <EmptyState title="Chưa có dòng món trong thực đơn tuần" /> : <><div className="planning-read-table"><table><caption className="sr-only">Dòng món theo ngày, ca, vị trí và số suất</caption><colgroup>{[34,14,12,10,15,15].map((width,index)=><col key={index} style={{width:`${width}%`}}/>)}</colgroup><thead><tr><th scope="col">Món / vị trí</th><th scope="col">Ca</th><th scope="col">BOM</th><th scope="col" data-cell-role="numeric">Suất</th><th scope="col" data-cell-role="numeric">Giá vốn / suất</th><th scope="col" data-cell-role="numeric">Thành tiền</th></tr></thead><tbody>{p.rows.map(row=><tr key={row.key}><td>{row.dishName}<small className="block text-slate-500">{row.slotLabel} · {row.menuTypeLabel}</small></td><td>{row.shiftLabel}</td><td>{row.hasCatalogBom ? 'Có BOM' : 'Thiếu BOM'}</td><td data-cell-role="numeric">{formatNumber(row.portions)}</td><td data-cell-role="numeric">{row.hasCatalogBom ? formatCurrency(row.unitCost) : '—'}</td><td data-cell-role="numeric">{row.hasCatalogBom ? formatCurrency(row.unitCost * row.portions) : '—'}</td></tr>)}</tbody></table></div><details><summary>Nguyên liệu dự kiến của ngày · {Object.keys(p.materialSummary).length} dòng</summary><div className="planning-read-table"><table><caption className="sr-only">BOM theo nguyên liệu và đơn vị trong ngày</caption><thead><tr><th scope="col">Nguyên liệu</th><th scope="col">Đơn vị</th><th scope="col" data-cell-role="numeric">Lượng BOM</th><th scope="col">Món nguồn</th></tr></thead><tbody>{Object.entries(p.materialSummary).map(([key,line])=><tr key={key}><td>{line.ingredientName}</td><td>{line.unit}</td><td data-cell-role="numeric">{formatQuantity(line.actual,{maximumFractionDigits:6})}</td><td>{line.dishNames.join(', ')}</td></tr>)}</tbody></table></div></details></>}
  </section>
}
