import { describe, expect, it } from 'vitest';

import { apiSlice } from '@/api/apiSlice';
import * as workflowModule from '@/api/workflowApi';

const expectedEndpointNames = [
  'cancelPurchaseOrder',
  'confirmInventoryIssueReceipt',
  'confirmInventoryReturnReceipt',
  'confirmLineSupplier',
  'createApprovalRule',
  'createInventoryIssue',
  'createInventoryReceiptFromPurchase',
  'createInventoryReturn',
  'createPurchaseOrdersFromRequest',
  'createPurchaseRequestFromDemand',
  'createSupplementalMaterialRequest',
  'createSupplierQuotation',
  'deactivateSupplierQuotation',
  'deleteApprovalRule',
  'executeApprovalDecision',
  'fulfillSupplementalMaterialRequest',
  'generateMaterialDemand',
  'getApprovalHistory',
  'getApprovalRecords',
  'getApprovalRules',
  'getAuditChangePage',
  'getAuditChanges',
  'getCurrentStock',
  'getCurrentStockPage',
  'getDailyProductionPlan',
  'getDataQuality',
  'getDataQualityPage',
  'getIngredientDemand',
  'getIngredientDemandAggregatePage',
  'getIngredientDemandPage',
  'getInventoryReturnById',
  'getInventoryReturns',
  'getIssueVsReturnUsage',
  'getIssueVsReturnUsagePage',
  'getKitchenIssues',
  'getKitchenIssuesPage',
  'getMaterialDemandStaleness',
  'getMaterialRequestCandidatePage',
  'getOperationalKpis',
  'getPriceVariance',
  'getPriceVarianceByDishGroup',
  'getPriceVarianceByDishGroupPage',
  'getPriceVarianceByPeriod',
  'getPriceVarianceByPeriodPage',
  'getPriceVarianceBySupplier',
  'getPriceVarianceBySupplierPage',
  'getPriceVariancePage',
  'getPurchaseOrders',
  'getPurchaseOrdersPage',
  'getPurchasePlan',
  'getPurchasePlanPage',
  'getPurchaseRequests',
  'getPurchaseRequestsPage',
  'getPurchaseWorkbench',
  'getStockLedgerReconciliation',
  'getStockMovementPage',
  'getStockMovements',
  'getSupplementalMaterialRequests',
  'getSupplierEvidence',
  'getSupplierQuotationsByIngredient',
  'getSupplierQuotationsByIngredientPage',
  'getSuppliers',
  'getWarehouseSelector',
  'getWarehouses',
  'getWorkflowDocuments',
  'recordPurchaseOrderReceipt',
  'recordWarehousePurchaseReceipt',
  'rejectSupplementalMaterialRequest',
  'routeSupplementalMaterialRequestToPurchasing',
  'sendDailyProductionPlanToKitchen',
  'submitPurchaseRequest',
  'updateApprovalRule',
  'updateDataQualityIssueRemediation',
  'updatePurchaseRequestLineSupplier',
  'updateSupplierQuotation',
] as const;

const expectedHookNames = [
  'useCancelPurchaseOrderMutation',
  'useConfirmInventoryIssueReceiptMutation',
  'useConfirmInventoryReturnReceiptMutation',
  'useConfirmLineSupplierMutation',
  'useCreateApprovalRuleMutation',
  'useCreateInventoryIssueMutation',
  'useCreateInventoryReceiptFromPurchaseMutation',
  'useCreateInventoryReturnMutation',
  'useCreatePurchaseOrdersFromRequestMutation',
  'useCreatePurchaseRequestFromDemandMutation',
  'useCreateSupplementalMaterialRequestMutation',
  'useCreateSupplierQuotationMutation',
  'useDeactivateSupplierQuotationMutation',
  'useDeleteApprovalRuleMutation',
  'useExecuteApprovalDecisionMutation',
  'useFulfillSupplementalMaterialRequestMutation',
  'useGenerateMaterialDemandMutation',
  'useGetApprovalHistoryQuery',
  'useGetApprovalRecordsQuery',
  'useGetApprovalRulesQuery',
  'useGetAuditChangePageQuery',
  'useGetAuditChangesQuery',
  'useGetCurrentStockPageQuery',
  'useGetCurrentStockQuery',
  'useGetDailyProductionPlanQuery',
  'useGetDataQualityPageQuery',
  'useGetDataQualityQuery',
  'useGetIngredientDemandAggregatePageQuery',
  'useGetIngredientDemandPageQuery',
  'useGetIngredientDemandQuery',
  'useGetInventoryReturnByIdQuery',
  'useGetInventoryReturnsQuery',
  'useGetIssueVsReturnUsagePageQuery',
  'useGetIssueVsReturnUsageQuery',
  'useGetKitchenIssuesPageQuery',
  'useGetKitchenIssuesQuery',
  'useGetMaterialDemandStalenessQuery',
  'useGetMaterialRequestCandidatePageQuery',
  'useGetOperationalKpisQuery',
  'useGetPriceVarianceByDishGroupPageQuery',
  'useGetPriceVarianceByDishGroupQuery',
  'useGetPriceVarianceByPeriodPageQuery',
  'useGetPriceVarianceByPeriodQuery',
  'useGetPriceVarianceBySupplierPageQuery',
  'useGetPriceVarianceBySupplierQuery',
  'useGetPriceVariancePageQuery',
  'useGetPriceVarianceQuery',
  'useGetPurchaseOrdersPageQuery',
  'useGetPurchaseOrdersQuery',
  'useGetPurchasePlanPageQuery',
  'useGetPurchasePlanQuery',
  'useGetPurchaseRequestsPageQuery',
  'useGetPurchaseRequestsQuery',
  'useGetPurchaseWorkbenchQuery',
  'useGetStockLedgerReconciliationQuery',
  'useGetStockMovementPageQuery',
  'useGetStockMovementsQuery',
  'useGetSupplementalMaterialRequestsQuery',
  'useGetSupplierEvidenceQuery',
  'useGetSupplierQuotationsByIngredientPageQuery',
  'useGetSupplierQuotationsByIngredientQuery',
  'useGetSuppliersQuery',
  'useGetWarehouseSelectorQuery',
  'useGetWarehousesQuery',
  'useGetWorkflowDocumentsQuery',
  'useRecordPurchaseOrderReceiptMutation',
  'useRecordWarehousePurchaseReceiptMutation',
  'useRejectSupplementalMaterialRequestMutation',
  'useRouteSupplementalMaterialRequestToPurchasingMutation',
  'useSendDailyProductionPlanToKitchenMutation',
  'useSubmitPurchaseRequestMutation',
  'useUpdateApprovalRuleMutation',
  'useUpdateDataQualityIssueRemediationMutation',
  'useUpdatePurchaseRequestLineSupplierMutation',
  'useUpdateSupplierQuotationMutation',
] as const;

describe('workflow API public surface', () => {
  it('registers the exact endpoint set on the one shared API slice', () => {
    expect(workflowModule.workflowApi).toBe(apiSlice);
    expect(workflowModule.workflowApi.reducerPath).toBe('api');
    expect(Object.keys(workflowModule.workflowApi.endpoints).sort()).toEqual(expectedEndpointNames);
  });

  it('keeps all generated public hooks exported by the compatibility module', () => {
    const hooks = Object.keys(workflowModule)
      .filter((name) => /^use[A-Z].*(?:Query|Mutation)$/.test(name))
      .sort();

    expect(hooks).toEqual(expectedHookNames);
    expect(hooks).toHaveLength(75);
  });
});
