import { apiSlice } from '@/api/apiSlice';
import { workflowDocumentsApi } from '@/api/workflowDocumentsApi';
import { dashboardApi } from '@/features/dashboard/dashboardApi';
import { reportsApi } from '@/features/reports/reportsApi';
import { purchasingApi } from '@/features/purchasing/purchasingApi';
import { warehouseApi } from '@/features/warehouse/warehouseApi';
import { chefApi } from '@/features/chef/chefApi';
import { approvalsApi } from '@/features/approvals/approvalsApi';
import { adminWorkflowApi } from '@/features/admin/adminWorkflowApi';

export const workflowApi = apiSlice as typeof apiSlice
  & typeof workflowDocumentsApi
  & typeof dashboardApi
  & typeof reportsApi
  & typeof purchasingApi
  & typeof warehouseApi
  & typeof chefApi
  & typeof approvalsApi
  & typeof adminWorkflowApi;

export type {
  WorkflowReportQuery,
  WorkflowReportPageQuery,
  DataQualityPageQuery,
  MaterialRequestCandidatePageQuery,
  CurrentStockPageQuery,
  ReceiptPriceVariancePageQuery,
  PriceVarianceAggregatePageQuery,
  PageNumberPage,
  CursorPage,
  ReportCursor,
  ApprovalInboxQuery,
  ApprovalInboxPage,
  PurchaseRequestQuery,
  PurchaseRequestResult,
  PurchaseWorkbenchQuery,
  PurchaseWorkflowStageCounts,
  SupplierEvidenceType,
  SupplierEvidenceCandidate,
  SupplierEvidenceResult,
  PurchaseLineSupplierDecision,
  PurchaseRequestWorkflowLine,
  ApprovedDemandSummary,
  PurchaseWorkbenchServiceDate,
  PurchaseWorkbenchWeek,
  SupplierEvidenceQuery,
  ConfirmPurchaseLineSupplierData,
  ConfirmPurchaseLineSupplierRequest,
  ApprovalHistoryItem,
  CreateInventoryReceiptFromPurchaseLineRequest,
  CreateInventoryReceiptFromPurchaseRequest,
  WarehouseDto,
  GeneratePurchaseRequestFromDemandRequest,
  PurchaseRequestWorkflowResult,
  InventoryReceiptCreatedResult,
  CreateInventoryIssueLineRequest,
  CreateInventoryIssueRequest,
  CreateSupplementalMaterialRequest,
  SupplementalMaterialRequestResult,
  SupplementalMaterialRequestPageQuery,
  InventoryIssueCreatedResult,
  CreateInventoryReturnLineRequest,
  CreateInventoryReturnRequest,
  InventoryReturnCreatedResult,
  ConfirmInventoryIssueReceiptRequest,
  InventoryIssueResult,
  MaterialRequestCandidate,
  PurchasePlanRow,
  ProductionPlanLine,
  ProductionPlan,
  DailyProductionPlan,
  SendDailyProductionPlanRequest,
    ServiceRunLifecycleProjectionDto,
    ServiceRunOperationalRowDto,
    ServiceRunPageResponseDto,
    ServiceRunPageQuery,
    ServiceRunByPlanQuery,
  OpenServiceRunRequest,
  RecordActualServingsRequest,
    ReasonRequest,
    CreateServiceRunAdjustmentRequest,
    ServiceRunAdjustmentDto,
  ApprovalRuleDto,
  ApprovalAssignmentDto,
  ApprovalAssignmentRequestDto,
  ApprovalRuleRequestDto,
  SupplierDto,
  UpdatePurchaseRequestLineSupplierDto,
  SupplierQuotationDto,
  CreateSupplierQuotationDto,
  UpdateSupplierQuotationDto,
  PurchaseOrderLineDto,
  InventoryReturnLineResult,
  InventoryReturnResult,
  InventoryReturnPageQuery,
  ConfirmInventoryReturnReceiptData,
  ConfirmInventoryReturnReceiptRequest,
  PurchaseOrderDto,
  PurchaseReceiptEvidenceRequirements,
  WarehousePurchaseReceiptLineRequest,
  WarehousePurchaseReceiptRequest,
  WarehousePurchaseReceiptResult,
  RecordWarehousePurchaseReceiptRequest,
  PurchaseOrderPageResponse,
  RecordPurchaseOrderReceiptLineDto,
  RecordPurchaseOrderReceiptDto,
  PriceVarianceBySupplierDto,
  PriceVarianceByPeriodDto,
  PriceVarianceDishGroupIngredientDto,
  PriceVarianceByDishGroupDto,
  OperationalKpiSummaryDto,
  GenerateMaterialDemandRequest,
  MaterialDemandStalenessQuery,
  MaterialDemandStaleness,
  ApprovalDecisionRequest,
  PriceVarianceRow,
  AuditLogRow,
  CurrentStockRow,
  StockLedgerReconciliationRow,
  KitchenIssueRow,
  UsageReportRow,
  DataQualityIssueRow,
  DataQualityReport,
  DataQualityPageReport,
  DataQualityIssueRemediationRequest,
  DataQualityIssueRemediationResult,
} from '@/api/workflowApiTypes';

export { toNextReportCursor } from '@/api/workflowApiTypes';

export {
  useGetWorkflowDocumentsQuery,
} from '@/api/workflowDocumentsApi';
export {
  useGetOperationalKpisQuery,
} from '@/features/dashboard/dashboardApi';
export {
  useGetIngredientDemandQuery,
  useGetPurchasePlanQuery,
  useGetPurchasePlanPageQuery,
  useGetIngredientDemandPageQuery,
  useGetMaterialRequestCandidatePageQuery,
  useGetIngredientDemandAggregatePageQuery,
  useGetStockMovementsQuery,
  useGetStockMovementPageQuery,
  useGetPriceVarianceQuery,
  useGetPriceVarianceBySupplierQuery,
  useGetPriceVarianceBySupplierPageQuery,
  useGetPriceVarianceByPeriodQuery,
  useGetPriceVarianceByPeriodPageQuery,
  useGetPriceVarianceByDishGroupQuery,
  useGetPriceVarianceByDishGroupPageQuery,
  useGetCurrentStockQuery,
  useGetStockLedgerReconciliationQuery,
  useGetKitchenIssuesQuery,
  useGetKitchenIssuesPageQuery,
  useGetIssueVsReturnUsageQuery,
  useGetIssueVsReturnUsagePageQuery,
  useGetAuditChangesQuery,
  useGetPriceVariancePageQuery,
  useGetCurrentStockPageQuery,
  useGetAuditChangePageQuery,
  useGetDataQualityQuery,
  useGetDataQualityPageQuery,
  useUpdateDataQualityIssueRemediationMutation,
} from '@/features/reports/reportsApi';
export {
  useGetSuppliersQuery,
  useGetPurchaseWorkbenchQuery,
  useGetSupplierEvidenceQuery,
  useConfirmLineSupplierMutation,
  useUpdatePurchaseRequestLineSupplierMutation,
  useGetSupplierQuotationsByIngredientQuery,
  useGetSupplierQuotationsByIngredientPageQuery,
  useCreateSupplierQuotationMutation,
  useUpdateSupplierQuotationMutation,
  useDeactivateSupplierQuotationMutation,
  useGetPurchaseOrdersQuery,
  useGetPurchaseOrdersPageQuery,
  useCreatePurchaseOrdersFromRequestMutation,
  useRecordPurchaseOrderReceiptMutation,
  useCancelPurchaseOrderMutation,
  useGenerateMaterialDemandMutation,
  useGetMaterialDemandStalenessQuery,
  useCreatePurchaseRequestFromDemandMutation,
  useSubmitPurchaseRequestMutation,
  useGetPurchaseRequestsQuery,
  useGetPurchaseRequestsPageQuery,
} from '@/features/purchasing/purchasingApi';
export {
  useGetWarehousesQuery,
  useGetWarehouseSelectorQuery,
  useRecordWarehousePurchaseReceiptMutation,
  useCreateInventoryReceiptFromPurchaseMutation,
  useCreateInventoryIssueMutation,
  useCreateSupplementalMaterialRequestMutation,
  useGetSupplementalMaterialRequestsQuery,
  useFulfillSupplementalMaterialRequestMutation,
  useRouteSupplementalMaterialRequestToPurchasingMutation,
  useRejectSupplementalMaterialRequestMutation,
  useCreateInventoryReturnMutation,
  useGetInventoryReturnsQuery,
  useGetInventoryReturnByIdQuery,
  useConfirmInventoryReturnReceiptMutation,
  useConfirmInventoryIssueReceiptMutation,
} from '@/features/warehouse/warehouseApi';
export {
  useGetDailyProductionPlanQuery,
  useSendDailyProductionPlanToKitchenMutation,
    useOpenServiceRunMutation,
    useGetServiceRunByPlanQuery,
    useGetServiceRunPageQuery,
  useStartServiceRunMutation,
  useRecordServiceRunActualServingsMutation,
    useConfirmServiceRunMutation,
    useResolveServiceRunVarianceMutation,
  useWaiveServiceRunConfirmationMutation,
    useCloseServiceRunMutation,
    useGetServiceRunAdjustmentsQuery,
    useCreateServiceRunAdjustmentMutation,
} from '@/features/chef/chefApi';
export {
  useGetApprovalRecordsQuery,
  useExecuteApprovalDecisionMutation,
  useGetApprovalHistoryQuery,
} from '@/features/approvals/approvalsApi';
export {
  useGetApprovalRulesQuery,
  useCreateApprovalRuleMutation,
  useUpdateApprovalRuleMutation,
  useDeleteApprovalRuleMutation,
} from '@/features/admin/adminWorkflowApi';

export { useWorkflowOverview } from '@/features/reports/reportsApi';
