/* eslint-disable @typescript-eslint/no-explicit-any */
import crypto from 'node:crypto'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import fixture from './fixtures/phase271-attempt-v2-sanitized-result.json' with { type:'json' }
import golden from './fixtures/phase271-golden-21-identities.json' with { type:'json' }
import { classifyExpectedVisualMismatches, hashGoldenManifest, sha256, type StructuredResult } from './visualReconciliationEvidence.ts'
import { runPhase271Playwright } from './runPhase271Playwright.ts'

const repo=path.resolve('.'),frontend=path.join(repo,'frontend'),phase='.planning/phases/27.1-reconcile-21-non-warehouse-visual-failures-before-phase-27-c',evidence=path.join(repo,phase,'evidence')
const canonicalInput={specs:['tests/visual-routes.spec.ts','tests/pagination-visual.spec.ts'],project:'chromium',workers:1,reporter:'json',config:'playwright.phase271-recovery.config.ts'}
const digestFile=(p:string)=>sha256(fs.readFileSync(p))
const atomicJson=(p:string,v:unknown)=>{fs.mkdirSync(path.dirname(p),{recursive:true});const t=`${p}.${crypto.randomUUID()}.tmp`;fs.writeFileSync(t,JSON.stringify(v,null,2)+'\n');const fd=fs.openSync(t,'r+');fs.fsyncSync(fd);fs.closeSync(fd);fs.renameSync(t,p)}
function flatten(report:any){const rows:any[]=[];function walk(suites:any[],parents:string[]=[]){for(const suite of suites||[]){const chain=[...parents,suite.title];for(const spec of suite.specs||[])for(const test of spec.tests||[])rows.push({project:test.projectName,normalizedSpecPath:`tests/${spec.file.replaceAll('\\','/').replace(/^tests\//,'')}`,canonicalTitle:[...chain,spec.title].join(' › '),test,result:test.results?.at(-1)});walk(suite.suites,chain)}}walk(report.suites);return rows}
const discovery=(report:any)=>flatten(report).map(({project,normalizedSpecPath,canonicalTitle})=>({project,normalizedSpecPath,canonicalTitle})).sort((a,b)=>`${a.project}\0${a.normalizedSpecPath}\0${a.canonicalTitle}`.localeCompare(`${b.project}\0${b.normalizedSpecPath}\0${b.canonicalTitle}`))
const discoveryHash=(rows:any[])=>sha256(JSON.stringify(rows))
function validatePackageScript(){const p=JSON.parse(fs.readFileSync(path.join(frontend,'package.json'),'utf8'));if(p.scripts?.['test:visual']!=='playwright test tests/visual-routes.spec.ts tests/pagination-visual.spec.ts')throw new Error('test:visual token drift')}
function sourceResults(report:any):StructuredResult[]{const goldenByThree=new Map(golden.identities.map(x=>[[x.project,x.normalizedSpecPath,x.canonicalTitle].join('\0'),x]));return flatten(report).map(({project,normalizedSpecPath,canonicalTitle,result})=>{const attachments=(result?.attachments||[]).map((a:any)=>({name:a.name,path:a.path,contentType:a.contentType}));const expected=attachments.find((a:any)=>a.name.endsWith('-expected.png'))?.name||'';const g=goldenByThree.get([project,normalizedSpecPath,canonicalTitle].join('\0'));const failed=result?.status==='failed';return {project,normalizedSpecPath,canonicalTitle,snapshotName:expected,viewport:g?.viewport||{width:1365,height:900},status:failed?'failed':'passed',failureKind:failed?(result.errors?.[0]?.message?.includes('toHaveScreenshot')?'screenshot-mismatch':'nonvisual'):undefined,attachments}})}
function preservePackets(report:any){const rows=sourceResults(report).filter(x=>x.status==='failed');const stage=path.join(evidence,`.packets-${crypto.randomUUID()}`);const members:any[]=[];fs.mkdirSync(stage,{recursive:true});rows.forEach((row,i)=>{const rowDir=path.join(stage,`row-${String(i+1).padStart(2,'0')}`);fs.mkdirSync(rowDir);const wanted=[['expected.png',row.attachments.find(a=>a.name.endsWith('-expected.png'))],['actual.png',row.attachments.find(a=>a.name.endsWith('-actual.png'))],['diff.png',row.attachments.find(a=>a.name.endsWith('-diff.png'))],['error-context.md',row.attachments.find(a=>a.name==='error-context')],['trace.zip',row.attachments.find(a=>a.name==='trace')]] as const;for(const [name,a] of wanted){if(!a?.path||!fs.existsSync(a.path))throw new Error(`missing packet source ${name}`);const dest=path.join(rowDir,name);fs.copyFileSync(a.path,dest);const fd=fs.openSync(dest,'r+');fs.fsyncSync(fd);fs.closeSync(fd);members.push({row:i+1,path:path.relative(repo,dest).replaceAll('\\','/').replace(/\.packets-[^/]+/,'packets'),sourcePath:path.relative(repo,a.path).replaceAll('\\','/'),sha256:digestFile(dest)})}})
 if(members.length!==105||new Set(members.map(x=>x.path)).size!==105)throw new Error('packet cardinality failure');const final=path.join(evidence,'packets');if(fs.existsSync(final))throw new Error('packets already exist');fs.renameSync(stage,final);return members}
async function main(){
 validatePackageScript();if(fixture.results.length!==76||hashGoldenManifest(golden.identities)!==golden.goldenIdentityManifestSha256)throw new Error('v2 fixture/golden hash drift');classifyExpectedVisualMismatches(fixture.results as StructuredResult[],golden.identities)
 const pre=await runPhase271Playwright(canonicalInput,'preflight');if(pre.exitCode!==0)throw new Error(`preflight failed: ${pre.stderr}`);const preReport=JSON.parse(pre.stdout);const preSet=discovery(preReport),fixtureSet=(fixture.results as StructuredResult[]).map(({project,normalizedSpecPath,canonicalTitle})=>({project,normalizedSpecPath,canonicalTitle})).sort((a,b)=>`${a.project}\0${a.normalizedSpecPath}\0${a.canonicalTitle}`.localeCompare(`${b.project}\0${b.normalizedSpecPath}\0${b.canonicalTitle}`)),preCanonicalHash=discoveryHash(preSet),preHash=fixture.discoverySha256;if(preSet.length!==76||JSON.stringify(preSet)!==JSON.stringify(fixtureSet)||!preSet.some(x=>x.normalizedSpecPath==='tests/pagination-visual.spec.ts')||preSet.some(x=>x.normalizedSpecPath.endsWith('.test.ts')))throw new Error(`discovery drift ${preSet.length} ${preCanonicalHash}`)
 if(process.argv.includes('--preflight-only')){console.log(JSON.stringify({status:'PASS',count:preSet.length,sha256:preHash,canonicalSetSha256:preCanonicalHash,attestation:pre.attestation}));return}
 const attemptId=`v3-${crypto.randomBytes(16).toString('hex')}`,runRoot=fs.mkdtempSync(path.join(os.tmpdir(),'phase271-v3-')),resultFile=path.join(runRoot,'playwright-results.json'),outputRoot=path.join(runRoot,'playwright-output');
 fs.mkdirSync(evidence,{recursive:true});const v2Path='D:/Temp/phase271-yyOJYU/playwright-results.json';const ledger:any={schemaVersion:1,attempts:[{attemptId:'source-1787417235040-30b20bd8-bdd7-45b5-abea-822243f58553',status:'REJECTED_SETUP',diagnosis:'D:/Kì',collectedIdentities:0,immutable:true},{attemptId:'v2-original-session-run',sessionId:'phase-27-1-plan-01-execution-v2',status:'REJECTED_CLASSIFIER',discoverySha256:fixture.discoverySha256,discoveredTests:76,screenshotFailures:21,structuredResult:{path:v2Path,sha256:digestFile(v2Path)},immutable:true},{attemptId,status:'AUTHORIZED',invocationCount:0,authorizedAfter:{classifier:true,argv:true,pathRoundTrip:true,discoverySha256:preHash}}]};atomicJson(path.join(evidence,'attempt-ledger.json'),ledger)
 ledger.attempts[2].invocationCount=1;ledger.attempts[2].status='RUNNING';atomicJson(path.join(evidence,'attempt-ledger.json'),ledger)
 const source=await runPhase271Playwright({...canonicalInput,outputRoot,env:{PLAYWRIGHT_JSON_OUTPUT_FILE:resultFile}},'source');fs.writeFileSync(path.join(runRoot,'stdout.log'),source.stdout);fs.writeFileSync(path.join(runRoot,'stderr.log'),source.stderr);if(!fs.existsSync(resultFile))throw new Error('source structured result missing');const report=JSON.parse(fs.readFileSync(resultFile,'utf8')),sourceSet=discovery(report);if(discoveryHash(sourceSet)!==preCanonicalHash||JSON.stringify(sourceSet)!==JSON.stringify(preSet))throw new Error('source/preflight discovery mismatch');classifyExpectedVisualMismatches(sourceResults(report),golden.identities)
 const members=preservePackets(report);ledger.attempts[2].status='ACCEPTED';ledger.attempts[2].exitCode=source.exitCode;ledger.attempts[2].attestation=source.attestation;atomicJson(path.join(evidence,'attempt-ledger.json'),ledger)
 const failures=sourceResults(report).filter(x=>x.status==='failed');atomicJson(path.join(evidence,'failure-inventory.json'),{schemaVersion:1,attemptId,discoverySha256:preHash,goldenIdentityManifestSha256:golden.goldenIdentityManifestSha256,failures:failures.map((x,i)=>({row:i+1,...golden.identities.find(g=>g.project===x.project&&g.normalizedSpecPath===x.normalizedSpecPath&&g.canonicalTitle===x.canonicalTitle&&g.snapshotName===x.snapshotName)}))});atomicJson(path.join(evidence,'packet-member-manifest.json'),{schemaVersion:1,attemptId,members});atomicJson(path.join(evidence,'source-run-manifest.json'),{schemaVersion:1,attemptId,status:'ACCEPTED',discoveredTests:76,failedScreenshotComparisons:21,memberCount:105,discoverySha256:preHash,attestation:source.attestation,structuredResultSha256:digestFile(resultFile)});console.log(JSON.stringify({status:'ACCEPTED',attemptId,members:members.length}))
}
main().catch(e=>{console.error(e);process.exitCode=1})
