import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { sha256 } from './validateVisualReconciliation.ts';

export const GENERAL_VALIDATOR_VERSION = '27.1-03R' as const;
const PHASE_DIR = '.planning/phases/27.1-reconcile-21-non-warehouse-visual-failures-before-phase-27-c';
const PLAN_IDS = ['27.1-02', '27.1-03R', '27.1-03', '27.1-04', '27.1-05', '27.1-06', '27.1-07'] as const;
export type Phase271PlanId = typeof PLAN_IDS[number];
type Schema = { resultPath: string; summaryPath: string; markerPath: string; resultKeys: readonly string[]; markerKeys: readonly string[]; predecessor?: Phase271PlanId };
const COMMON_RESULT = ['schemaVersion','phase','planId','status','summary','authorityRoots','validationHashes','tests','browserRun','productionChanged','snapshotsChanged','blockers'] as const;
const COMMON_MARKER = ['schemaVersion','phase','planId','status','authority','payloadCommit','summary','payloadResult','authorityRoots','dependencies','validationHashes','blockers'] as const;
const schema = (id: Phase271PlanId, predecessor?: Phase271PlanId): Schema => ({
  resultPath: `${PHASE_DIR}/evidence/plan-results/${id}.json`, summaryPath: `${PHASE_DIR}/${id}-SUMMARY.md`, markerPath: `${PHASE_DIR}/evidence/terminal-markers/${id}.json`, resultKeys: COMMON_RESULT, markerKeys: COMMON_MARKER, predecessor,
});
export const PLAN_SCHEMAS: Readonly<Record<Phase271PlanId, Schema>> = Object.freeze({
  '27.1-02': { ...schema('27.1-02'), resultKeys: ['schemaVersion','phase','planId','status','waveBaseCommit','currentHead','partialCommit','partialDisposition','summary','authorityRoots','validationHashes','tests','browserRun','productionChanged','snapshotsChanged','blockers'], markerKeys: ['schemaVersion','phase','planId','status','authority','waveBaseCommit','payloadCommit','summary','payloadResult','partialCommit','partialDisposition','authorityRoots','orderedCommits','validationHashes','blockers'] },
  '27.1-03R': { ...schema('27.1-03R','27.1-02'), resultPath: `${PHASE_DIR}/evidence/plan-results/27.1-03R.json`, markerPath: `${PHASE_DIR}/evidence/terminal-markers/27.1-03R-general-validator.json`, resultKeys: [...COMMON_RESULT,'manifest','predecessor'], markerKeys: [...COMMON_MARKER,'manifest','validatorPins'] },
  '27.1-03': schema('27.1-03','27.1-02'), '27.1-04': schema('27.1-04','27.1-03'), '27.1-05': schema('27.1-05','27.1-04'), '27.1-06': schema('27.1-06','27.1-05'), '27.1-07': schema('27.1-07','27.1-06'),
});

function object(value: unknown, label: string): asserts value is Record<string, any> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(`${label} must be an object`); }
function closed(value: unknown, keys: readonly string[], label: string): asserts value is Record<string, any> { object(value,label); const actual=Object.keys(value); const extra=actual.filter(k=>!keys.includes(k)); const missing=keys.filter(k=>!actual.includes(k)); if(extra.length||missing.length) throw new Error(`${label} schema mismatch; extra=${extra} missing=${missing}`); }
function artifact(value: unknown, path: string, label: string) { closed(value,['path','sha256'],label); if(value.path!==path || !/^[a-f0-9]{64}$/.test(value.sha256)) throw new Error(`${label} pin mismatch`); }
function roots(value: unknown, count: number) { if(!Array.isArray(value)||value.length!==count) throw new Error(`exact ${count} authority roots required`); const types=new Set<string>(), paths=new Set<string>(), commits=new Set<string>(); for(const [i,r] of value.entries()){ object(r,`root ${i}`); for(const k of ['type','path','sha256','commit']) if(typeof r[k]!=='string'||!r[k]) throw new Error(`root ${i}.${k} required`); if(!/^[a-f0-9]{64}$/.test(r.sha256)||!/^[a-f0-9]{40}$/.test(r.commit)) throw new Error('root pin invalid'); types.add(r.type);paths.add(r.path);commits.add(r.commit); } if(types.size!==count||paths.size!==count||commits.size!==count) throw new Error('authority roots collapse/duplicate'); }
function dependencies(value: unknown, predecessor?: string){ if(!predecessor){ if(value!==undefined) throw new Error('unexpected dependencies'); return; } if(!Array.isArray(value)||value.length!==1) throw new Error('exact dependency required'); const d=value[0]; closed(d,['planId','marker','sha256','commit'], 'dependency'); if(d.planId!==predecessor||!/^[a-f0-9]{64}$/.test(d.sha256)||!/^[a-f0-9]{40}$/.test(d.commit)) throw new Error('dependency mismatch'); }
export function validatePhase271PlanResult(planId: string, value: unknown){ const s=(PLAN_SCHEMAS as Record<string,Schema>)[planId]; if(!s) throw new Error('plan ID is not allowlisted'); closed(value,s.resultKeys,'result'); if(value.planId!==planId||value.phase!=='27.1'||value.schemaVersion!==1||value.status!=='READY_TO_SEAL') throw new Error('result identity/status mismatch'); artifact(value.summary,s.summaryPath,'summary'); roots(value.authorityRoots,planId==='27.1-02'?7:8); if(!value.validationHashes||typeof value.validationHashes!=='object'||Array.isArray(value.validationHashes)||!Object.values(value.validationHashes).every(v=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v))) throw new Error('validation hashes invalid'); if(!Array.isArray(value.blockers)||value.blockers.length) throw new Error('blockers must be empty'); if(planId==='27.1-03R'){ artifact(value.manifest,`${PHASE_DIR}/evidence/attestations/27.1-03R-general-validator-manifest.json`,'manifest'); if(value.predecessor!=='27.1-02') throw new Error('predecessor mismatch'); } }
export function validatePhase271PlanMarker(planId:string,value:unknown){ const s=(PLAN_SCHEMAS as Record<string,Schema>)[planId]; if(!s) throw new Error('plan ID is not allowlisted'); closed(value,s.markerKeys,'marker'); if(value.planId!==planId||value.phase!=='27.1'||value.schemaVersion!==1||value.status!=='COMPLETE'||!/^[a-f0-9]{40}$/.test(value.payloadCommit)) throw new Error('marker identity/status/commit mismatch'); artifact(value.summary,s.summaryPath,'summary'); artifact(value.payloadResult,s.resultPath,'payload result'); roots(value.authorityRoots,planId==='27.1-02'?7:8); if(planId!=='27.1-02') dependencies(value.dependencies,s.predecessor); if(planId==='27.1-03R'){ artifact(value.manifest,`${PHASE_DIR}/evidence/attestations/27.1-03R-general-validator-manifest.json`,'manifest'); if(!Array.isArray(value.validatorPins)||value.validatorPins.length!==4) throw new Error('exact four validator pins required'); } }
const git=(...args:string[])=>execFileSync('git',args,{encoding:'utf8'}).trim();
function verifyArtifact(item:any){ if(sha256(readFileSync(resolve(item.path)))!==item.sha256) throw new Error(`artifact hash mismatch: ${item.path}`); }
export function validateCommittedPlan(planId:Phase271PlanId, marker:any){ const s=PLAN_SCHEMAS[planId]; validatePhase271PlanMarker(planId,marker); verifyArtifact(marker.summary);verifyArtifact(marker.payloadResult); for(const root of marker.authorityRoots){ if(git('cat-file','-t',root.commit)!=='commit') throw new Error(`root commit is unreachable: ${root.type}`); if(sha256(readFileSync(resolve(root.path)))!==root.sha256) throw new Error(`root hash mismatch: ${root.type}`); } const result=JSON.parse(readFileSync(resolve(marker.payloadResult.path),'utf8'));validatePhase271PlanResult(planId,result); const markerCommit=git('log','-n','1','--format=%H','--',s.markerPath); const markerMembers=git('diff-tree','--no-commit-id','--name-only','-r',markerCommit).split(/\r?\n/).filter(Boolean); if(markerMembers.length!==1||markerMembers[0]!==s.markerPath) throw new Error('marker commit is not marker-only'); if(git('rev-parse',`${markerCommit}^`)!==marker.payloadCommit) throw new Error('marker is not immediate payload child'); if(git('merge-base',marker.payloadCommit,markerCommit)!==marker.payloadCommit) throw new Error('merge ancestry rejected'); const payloadMembers=git('diff-tree','--no-commit-id','--name-only','-r',marker.payloadCommit).split(/\r?\n/).filter(Boolean); for(const p of [s.summaryPath,s.resultPath]) if(!payloadMembers.includes(p)) throw new Error(`payload missing ${p}`); if(s.predecessor){ const d=marker.dependencies[0]; const expected=git('log','-n','1','--format=%H','--',d.marker); if(expected!==d.commit||sha256(readFileSync(resolve(d.marker)))!==d.sha256) throw new Error('dependency pin mismatch'); } return {markerCommit,payloadCommit:marker.payloadCommit}; }
function main(){ const args=process.argv.slice(2), val=(n:string)=>args[args.indexOf(n)+1]; const id=val('--plan') as Phase271PlanId; if(!(id in PLAN_SCHEMAS)||val('--require')!=='COMPLETE') throw new Error('closed plan and COMPLETE required'); const marker=JSON.parse(readFileSync(resolve(PLAN_SCHEMAS[id].markerPath),'utf8')); const out=validateCommittedPlan(id,marker); console.log(`PASS ${id} COMPLETE payload=${out.payloadCommit} marker=${out.markerCommit}`); }
if(process.argv[1]&&fileURLToPath(import.meta.url)===resolve(process.argv[1])) main();
