import { useMemo, useState } from 'react'
import { useSystemOperation } from '@/features/system-operation/systemOperationContext'
import { ReconciliationBatchTable } from './ReconciliationBatchTable'
import { ReconciliationComparisonTable } from './ReconciliationComparisonTable'
import { ReconciliationActualDrawer } from './ReconciliationActualDrawer'
import { useCompleteReconciliationBatchMutation, useListReconciliationBatchesQuery, useReadyReconciliationBatchMutation, type ReconciliationLine } from './reconciliationApi'

export function ReconciliationWorkspace({ owner }: { owner:'weekly-menu'|'purchasing'|'warehouse'|'reports' }) { const mode=useSystemOperation(); if(mode?.mode!=='MATERIAL_RECONCILIATION')return null; return <ActiveReconciliationWorkspace owner={owner} /> }
function ActiveReconciliationWorkspace({ owner }: { owner:'weekly-menu'|'purchasing'|'warehouse'|'reports' }) { const {data=[],isLoading,isError}=useListReconciliationBatchesQuery(); const [selectedId,setSelectedId]=useState<string>(); const [showAll,setShowAll]=useState(false); const [editing,setEditing]=useState<ReconciliationLine>(); const selected=useMemo(()=>data.find(x=>x.batchId===(selectedId??data[0]?.batchId)),[data,selectedId]); const [ready]=useReadyReconciliationBatchMutation(); const [complete]=useCompleteReconciliationBatchMutation(); return <section className="mt-6 space-y-4 rounded-lg border border-slate-200 bg-white p-4" aria-label="Đối chiếu nguyên liệu"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-lg font-semibold">Đối chiếu nguyên liệu</h2><p className="text-sm text-slate-600">Số liệu riêng của lô, không tạo phiếu mua, nhập, xuất hoặc biến động tồn.</p></div>{selected&&owner==='weekly-menu'&&selected.status==='DRAFT'&&<button className="rounded bg-blue-700 px-3 py-2 text-white" onClick={()=>ready({id:selected.batchId,expectedVersion:selected.version})}>Sẵn sàng đối chiếu</button>}{selected&&owner==='reports'&&selected.status==='IN_PROGRESS'&&<button className="rounded bg-blue-700 px-3 py-2 text-white" onClick={()=>complete({id:selected.batchId,expectedVersion:selected.version})}>Hoàn tất đối chiếu</button>}</div>{isLoading?<p>Đang tải lô đối chiếu...</p>:isError?<p role="alert">Không tải được lô đối chiếu.</p>:data.length===0?<p>Chưa có lô đối chiếu.</p>:<><ReconciliationBatchTable batches={data} selectedId={selected?.batchId} onSelect={setSelectedId}/>{selected&&<><div className="flex justify-end"><button type="button" className="text-sm text-blue-700" onClick={()=>setShowAll(x=>!x)}>{showAll?'Chỉ hiện dòng cần xử lý':'Hiện tất cả'}</button></div><ReconciliationComparisonTable lines={selected.lines} showAll={showAll} onEdit={owner==='purchasing'||owner==='warehouse'?setEditing:undefined}/></>}</>}{editing&&<ReconciliationActualDrawer line={editing} side={owner==='warehouse'?'issued':'purchased'} onClose={()=>setEditing(undefined)}/>}</section> }
