import { Button } from '@/components/ui/button'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { formatQuantity } from '@/lib/formatters'
import type { ReconciliationLine } from './reconciliationApi'

export function ReconciliationComparisonTable({ lines, showAll = false, onEdit, onDisposition }: { lines: ReconciliationLine[]; showAll?: boolean; onEdit?: (line: ReconciliationLine) => void; onDisposition?: (line: ReconciliationLine) => void }) {
  const visible = showAll ? lines : lines.filter((line) => line.status !== 'MATCHED')
  return <div><Table aria-label="Kết quả đối chiếu nguyên liệu"><TableHeader><TableRow><TableHead>Nguyên liệu</TableHead><TableHead>Cần</TableHead><TableHead>Đã mua</TableHead><TableHead>Đã xuất</TableHead><TableHead>Mua − cần</TableHead><TableHead>Xuất − cần</TableHead><TableHead>Mua − xuất</TableHead><TableHead>Kết quả</TableHead><TableHead>Thao tác</TableHead></TableRow></TableHeader><TableBody>{visible.map((line) => <TableRow key={line.batchLineId}><TableCell title={line.ingredientId}>…{line.ingredientId.slice(-8)}</TableCell><TableCell>{formatQuantity(line.requiredQuantity, { maximumFractionDigits: 6 })}</TableCell><TableCell>{line.purchasedQuantity == null ? 'Chưa nhập' : formatQuantity(line.purchasedQuantity, { maximumFractionDigits: 6 })}</TableCell><TableCell>{line.issuedQuantity == null ? 'Chưa nhập' : formatQuantity(line.issuedQuantity, { maximumFractionDigits: 6 })}</TableCell><TableCell>{line.purchasedRequiredDifference == null ? '—' : formatQuantity(line.purchasedRequiredDifference, { maximumFractionDigits: 6 })}</TableCell><TableCell>{line.issuedRequiredDifference == null ? '—' : formatQuantity(line.issuedRequiredDifference, { maximumFractionDigits: 6 })}</TableCell><TableCell>{line.purchasedIssuedDifference == null ? '—' : formatQuantity(line.purchasedIssuedDifference, { maximumFractionDigits: 6 })}</TableCell><TableCell>{line.status === 'MATCHED' ? 'Khớp' : line.status === 'NEEDS_REVIEW' ? 'Cần kiểm tra' : 'Chưa đủ số liệu'}</TableCell><TableCell><div className="flex flex-col items-start gap-1">{onEdit && <Button type="button" variant="link" className="h-auto p-0" onClick={() => onEdit(line)}>Cập nhật số liệu</Button>}{onDisposition && line.status === 'NEEDS_REVIEW' && <Button type="button" variant="link" className="h-auto p-0" onClick={() => onDisposition(line)}>{line.disposition ? 'Sửa xử lý' : 'Xử lý chênh lệch'}</Button>}</div></TableCell></TableRow>)}</TableBody></Table>{visible.length === 0 && <p className="p-4 text-sm text-slate-600">Không có dòng cần kiểm tra.</p>}</div>
}
