using System.Reflection;
using System.Reflection.Emit;
using FluentAssertions;
using IPCManagement.Api.Data;
using IPCManagement.Api.Infrastructure.LifecycleOutbox;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.AspNetCore.Mvc.ActionConstraints;
using Microsoft.AspNetCore.Mvc.Controllers;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Routing;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace IPCManagement.Api.Tests;

internal static class Phase30FinalOracleContracts
{
    internal static void AssertExactMutationSurface()
    {
        var actual = DiscoverMutationSurface();
        actual.Select(Serialize).Should().Equal(CurrentProductionMutationActions,
            "every effective production non-read MVC action is a reviewed closed-surface contract; copy the failure output only after reviewing the changed route/signature/dependencies");
    }

    internal static void AssertExactLifecycleRegistrationsAndCapabilities()
    {
        using var sqlite = new SqliteConnection("Data Source=:memory:");
        sqlite.Open();
        var configuration = new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string, string?>()).Build();
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddBackendServicesCore(configuration, options => options.UseSqlite(sqlite));

        var descriptors = services.Select((descriptor, index) => Describe(descriptor, index)).ToArray();
        descriptors.Where(x => x.ServiceType == Full(typeof(ILifecycleOutboxProcessor)))
            .Select(x => x.Contract).Should().Equal($"{Full(typeof(ILifecycleOutboxProcessor))}|Scoped|type:{Full(typeof(LifecycleOutboxProcessor))}");
        descriptors.Where(x => x.ServiceType == Full(typeof(ILifecycleOutboxConsumer)))
            .Select(x => x.Contract).Should().Equal($"{Full(typeof(ILifecycleOutboxConsumer))}|Scoped|type:{Full(typeof(LifecyclePayloadValidationConsumer))}");

        using var provider = services.BuildServiceProvider(new ServiceProviderOptions { ValidateScopes = true, ValidateOnBuild = false });
        using var scope = provider.CreateScope();
        scope.ServiceProvider.GetRequiredService<ILifecycleOutboxProcessor>().Should().BeOfType<LifecycleOutboxProcessor>();
        scope.ServiceProvider.GetServices<ILifecycleOutboxConsumer>().Select(x => x.GetType()).Should().Equal(typeof(LifecyclePayloadValidationConsumer));
        var hosted = provider.GetServices<IHostedService>().Select(x => x.GetType()).ToArray();
        hosted.Should().Equal(typeof(LifecycleOutboxWorker));
        descriptors.Where(x => x.ServiceType == Full(typeof(IHostedService))).Select(x => x.Contract)
            .Should().Equal($"{Full(typeof(IHostedService))}|Singleton|type:{Full(typeof(LifecycleOutboxWorker))}");

        AssertConstructors(typeof(LifecycleOutboxProcessor),
            Full(typeof(IpcManagementContext)),
            $"System.Collections.Generic.IEnumerable`1[{Full(typeof(ILifecycleOutboxConsumer))}]",
            "Microsoft.Extensions.Options.IOptions`1[IPCManagement.Api.Infrastructure.LifecycleOutbox.LifecycleOutboxOptions]",
            Full(typeof(TimeProvider)),
            "Microsoft.Extensions.Logging.ILogger`1[IPCManagement.Api.Infrastructure.LifecycleOutbox.LifecycleOutboxProcessor]");
        AssertConstructors(typeof(LifecycleOutboxWorker),
            Full(typeof(IServiceScopeFactory)),
            "Microsoft.Extensions.Options.IOptions`1[IPCManagement.Api.Infrastructure.LifecycleOutbox.LifecycleOutboxOptions]",
            "Microsoft.Extensions.Logging.ILogger`1[IPCManagement.Api.Infrastructure.LifecycleOutbox.LifecycleOutboxWorker]");
        AssertConstructors(typeof(LifecyclePayloadValidationConsumer));

        AssertExactCapabilitySurface();
        AssertDeliveryOnlyIlClosure(typeof(LifecycleOutboxProcessor), typeof(LifecycleOutboxWorker), typeof(LifecyclePayloadValidationConsumer));
    }

    private static MutationActionContract[] DiscoverMutationSurface()
    {
        var builder = new WebHostBuilder().Configure(_ => { }).ConfigureServices(services =>
            services.AddControllers().AddApplicationPart(typeof(IPCManagement.Api.DependencyInjection).Assembly));
        using var server = new TestServer(builder);
        var provider = server.Services.GetRequiredService<IActionDescriptorCollectionProvider>();
        var actions = provider.ActionDescriptors.Items.OfType<ControllerActionDescriptor>()
            .Where(action =>
            {
                var methods = action.ActionConstraints?.OfType<HttpMethodActionConstraint>().SelectMany(x => x.HttpMethods).ToArray();
                return methods is null || methods.Length == 0 || methods.Any(method => method is not ("GET" or "HEAD" or "OPTIONS"));
            })
            .Select(action => new MutationActionContract(
                Full(action.ControllerTypeInfo.AsType()), action.ActionName,
                (action.ActionConstraints?.OfType<HttpMethodActionConstraint>().SelectMany(x => x.HttpMethods).Distinct(StringComparer.Ordinal).OrderBy(x => x, StringComparer.Ordinal).ToArray()) ?? [],
                action.AttributeRouteInfo?.Template ?? "<conventional>", Signature(action.MethodInfo),
                action.ControllerTypeInfo.DeclaredConstructors.Where(x => x.IsPublic).Select(x => x.GetParameters().Select(ParameterContract).ToArray()).OrderBy(x => string.Join("|", x), StringComparer.Ordinal).ToArray(),
                action.Parameters.OfType<ControllerParameterDescriptor>().Where(x => x.BindingInfo?.BindingSource == BindingSource.Services || x.ParameterInfo.GetCustomAttributes().Any(a => a.GetType().Name.Contains("FromKeyedServices", StringComparison.Ordinal)))
                    .Select(x => ParameterContract(x.ParameterInfo)).OrderBy(x => x, StringComparer.Ordinal).ToArray()))
            .OrderBy(x => x.ControllerFullName, StringComparer.Ordinal).ThenBy(x => x.ActionName, StringComparer.Ordinal)
            .ThenBy(x => x.EffectiveRoute, StringComparer.Ordinal).ThenBy(x => string.Join(",", x.HttpMethods), StringComparer.Ordinal).ThenBy(x => x.MethodSignature, StringComparer.Ordinal).ToArray();
        actions.GroupBy(x => $"{x.ControllerFullName}|{x.ActionName}|{string.Join(',', x.HttpMethods)}|{x.EffectiveRoute}|{x.MethodSignature}", StringComparer.Ordinal)
            .Should().OnlyContain(x => x.Count() == 1, "canonical MVC mutation keys must be unique");
        return actions;
    }

    private static DescriptorContract Describe(ServiceDescriptor descriptor, int index)
    {
        var serviceType = Full(descriptor.ServiceType);
        var shape = descriptor.ImplementationType is not null ? "type" : descriptor.ImplementationInstance is not null ? "instance" : "factory";
        var implementation = descriptor.ImplementationType is not null ? Full(descriptor.ImplementationType)
            : descriptor.ImplementationInstance is not null ? Full(descriptor.ImplementationInstance.GetType()) : "<realized-in-scope>";
        return new(serviceType, shape, $"{serviceType}|{descriptor.Lifetime}|{shape}:{implementation}");
    }

    private static void AssertConstructors(Type type, params string[] expected)
    {
        type.GetConstructors(BindingFlags.Public | BindingFlags.Instance).Should().ContainSingle().Which.GetParameters()
            .Select(x => Full(x.ParameterType)).Should().Equal(expected);
    }

    private static void AssertExactCapabilitySurface()
    {
        Surface(typeof(ILifecycleOutboxProcessor)).Should().Equal(
            "method:public:System.Threading.Tasks.Task`1[System.Int32] IPCManagement.Api.Infrastructure.LifecycleOutbox.ILifecycleOutboxProcessor.ProcessBatchAsync`0(System.Threading.CancellationToken cancellationToken)");
        Surface(typeof(ILifecycleOutboxConsumer)).Should().Equal(
            "method:public:System.Threading.Tasks.Task IPCManagement.Api.Infrastructure.LifecycleOutbox.ILifecycleOutboxConsumer.ConsumeAsync`0(IPCManagement.Api.Models.Entities.LifecycleOutboxMessage message,System.Threading.CancellationToken cancellationToken)",
            "property:public:System.String ConsumerName{get}");
        Surface(typeof(LifecyclePayloadValidationConsumer)).Should().Equal(
            "interface:IPCManagement.Api.Infrastructure.LifecycleOutbox.ILifecycleOutboxConsumer",
            "method:public:System.Threading.Tasks.Task IPCManagement.Api.Infrastructure.LifecycleOutbox.LifecyclePayloadValidationConsumer.ConsumeAsync`0(IPCManagement.Api.Models.Entities.LifecycleOutboxMessage message,System.Threading.CancellationToken cancellationToken)",
            "property:public:System.String ConsumerName{get}");
    }

    private static string[] Surface(Type type) => type.GetInterfaces().Where(x => x.Assembly == type.Assembly).Select(x => $"interface:{Full(x)}")
        .Concat(type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly).Where(x => !x.IsSpecialName).Select(x => $"method:public:{Signature(x)}"))
        .Concat(type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly).Select(x => $"property:public:{Full(x.PropertyType)} {x.Name}{{{(x.GetMethod is null ? "" : "get")}{(x.SetMethod is null ? "" : ";set")}}}"))
        .OrderBy(x => x, StringComparer.Ordinal).ToArray();

    private static void AssertDeliveryOnlyIlClosure(params Type[] roots)
    {
        var production = typeof(IPCManagement.Api.DependencyInjection).Assembly;
        var forbidden = new[] { "MaterialRequest", "ReconciliationBatch", "DbSet`1[IPCManagement.Api.Models.Entities.Material", "DbSet`1[IPCManagement.Api.Models.Entities.Reconciliation", "ExecuteSql", "FromSql", "System.Reflection", "System.Delegate" };
        var queue = new Queue<MethodBase>(roots.SelectMany(AllMethods));
        var visited = new HashSet<MethodBase>();
        while (queue.TryDequeue(out var method))
        {
            if (!visited.Add(method)) continue;
            foreach (var member in ResolveIlMembers(method))
            {
                var identity = $"{member.DeclaringType?.FullName}.{member.Name}";
                identity.Should().NotContainAny(forbidden, $"the exact registered lifecycle IL closure at {method.DeclaringType?.FullName}.{method.Name} is limited to delivery state");
                if (member is MethodBase called && called.DeclaringType?.Assembly == production && IsOwnedByRoots(called.DeclaringType, roots)) queue.Enqueue(called);
            }
        }
    }

    private static bool IsOwnedByRoots(Type type, Type[] roots) => roots.Contains(type) || roots.Any(root => type.FullName?.StartsWith(root.FullName + "+", StringComparison.Ordinal) == true);
    private static IEnumerable<MethodBase> AllMethods(Type type) => type.GetMethods(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic).Cast<MethodBase>().Concat(type.GetConstructors(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic));

    private static IEnumerable<MemberInfo> ResolveIlMembers(MethodBase method)
    {
        var body = method.GetMethodBody();
        if (body is null) yield break;
        var bytes = body.GetILAsByteArray()!;
        for (var offset = 0; offset < bytes.Length;)
        {
            var op = bytes[offset++] == 0xfe ? MultiByte[bytes[offset++]] : SingleByte[bytes[offset - 1]];
            var size = OperandSize(op.OperandType, bytes, offset);
            if (op.OperandType is OperandType.InlineField or OperandType.InlineMethod or OperandType.InlineTok or OperandType.InlineType)
            {
                var token = BitConverter.ToInt32(bytes, offset);
                MemberInfo member;
                try { member = method.Module.ResolveMember(token, method.DeclaringType?.GetGenericArguments(), method is MethodInfo mi ? mi.GetGenericArguments() : null)!; }
                catch (Exception ex) { throw new InvalidOperationException($"Unresolved production IL token 0x{token:X8} in {method.DeclaringType?.FullName}.{method.Name}.", ex); }
                yield return member;
            }
            offset += size;
        }
    }

    private static int OperandSize(OperandType type, byte[] bytes, int offset) => type switch
    {
        OperandType.InlineNone => 0, OperandType.ShortInlineBrTarget or OperandType.ShortInlineI or OperandType.ShortInlineVar => 1,
        OperandType.InlineVar => 2, OperandType.InlineI or OperandType.InlineBrTarget or OperandType.InlineField or OperandType.InlineMethod or OperandType.InlineSig or OperandType.InlineString or OperandType.InlineTok or OperandType.InlineType or OperandType.ShortInlineR => 4,
        OperandType.InlineI8 or OperandType.InlineR => 8,
        OperandType.InlineSwitch => 4 + BitConverter.ToInt32(bytes, offset) * 4,
        _ => throw new InvalidOperationException($"Unsupported IL operand {type}.")
    };

    private static string Signature(MethodInfo method) => $"{Full(method.ReturnType)} {Full(method.DeclaringType!)}.{method.Name}`{method.GetGenericArguments().Length}({string.Join(',', method.GetParameters().Select(ParameterContract))})";
    private static string ParameterContract(ParameterInfo p) => $"{(p.ParameterType.IsByRef ? p.IsOut ? "out " : p.IsIn ? "in " : "ref " : "")}{Full(p.ParameterType.IsByRef ? p.ParameterType.GetElementType()! : p.ParameterType)} {p.Name}{(Nullability.Create(p).ReadState == NullabilityState.Nullable ? "?" : "")}";
    private static string Full(Type type) => type.IsGenericType ? $"{type.GetGenericTypeDefinition().FullName![..^2]}`{type.GetGenericArguments().Length}[{string.Join(',', type.GetGenericArguments().Select(Full))}]" : type.FullName ?? type.Name;
    private static string Serialize(MutationActionContract x) => $"{x.ControllerFullName}|{x.ActionName}|{string.Join(',', x.HttpMethods)}|{x.EffectiveRoute}|{x.MethodSignature}|ctors={string.Join(';', x.PublicConstructorContracts.Select(c => string.Join(',', c)))}|injected={string.Join(',', x.ActionInjectedContracts)}";

    private static readonly NullabilityInfoContext Nullability = new();
    private static readonly OpCode[] SingleByte = BuildOpcodes(false);
    private static readonly OpCode[] MultiByte = BuildOpcodes(true);
    private static OpCode[] BuildOpcodes(bool multi)
    {
        var result = new OpCode[256];
        foreach (var field in typeof(OpCodes).GetFields(BindingFlags.Public | BindingFlags.Static))
        {
            var op = (OpCode)field.GetValue(null)!;
            if ((op.Size == 2) == multi) result[(byte)op.Value] = op;
        }
        return result;
    }

    private static readonly string[] CurrentProductionMutationActions = """
IPCManagement.Api.Features.Admin.Controllers.AdminEmployeesController|Create|POST|api/admin/employees|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Admin.Controllers.AdminEmployeesController.CreateAsync`0(IPCManagement.Api.Features.Admin.Contracts.CreateEmployeeRequest request)|ctors=IPCManagement.Api.Features.Admin.Services.IAdminEmployeeService employeeService|injected=
IPCManagement.Api.Features.Admin.Controllers.AdminEmployeesController|SeedSampleUsers|POST|api/admin/employees/seed|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Admin.Controllers.AdminEmployeesController.SeedSampleUsersAsync`0(Microsoft.Extensions.Hosting.IHostEnvironment environment)|ctors=IPCManagement.Api.Features.Admin.Services.IAdminEmployeeService employeeService|injected=Microsoft.Extensions.Hosting.IHostEnvironment environment
IPCManagement.Api.Features.Admin.Controllers.AdminEmployeesController|Update|PUT|api/admin/employees/{id}|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Admin.Controllers.AdminEmployeesController.UpdateAsync`0(System.String id,IPCManagement.Api.Features.Admin.Contracts.UpdateEmployeeRequest request,IPCManagement.Api.Security.ICurrentUserService currentUserService)|ctors=IPCManagement.Api.Features.Admin.Services.IAdminEmployeeService employeeService|injected=IPCManagement.Api.Security.ICurrentUserService currentUserService
IPCManagement.Api.Features.Admin.Controllers.AdminEmployeesController|UpdateStatus|PATCH|api/admin/employees/{id}/status|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Admin.Controllers.AdminEmployeesController.UpdateStatusAsync`0(System.String id,IPCManagement.Api.Features.Admin.Contracts.UpdateEmployeeStatusRequest request,IPCManagement.Api.Security.ICurrentUserService currentUserService)|ctors=IPCManagement.Api.Features.Admin.Services.IAdminEmployeeService employeeService|injected=IPCManagement.Api.Security.ICurrentUserService currentUserService
IPCManagement.Api.Features.Admin.Controllers.LifecycleOutboxController|Replay|POST|api/admin/lifecycle-outbox/{messageId}/replay|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Admin.Controllers.LifecycleOutboxController.ReplayAsync`0(System.String messageId,IPCManagement.Api.Infrastructure.LifecycleOutbox.ReplayLifecycleOutboxRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Infrastructure.LifecycleOutbox.ILifecycleOutboxAdminService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Approvals.Controllers.ApprovalRulesController|CreateRule|POST|api/approval-rules|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Approvals.Controllers.ApprovalRulesController.CreateRuleAsync`0(IPCManagement.Api.Features.Approvals.Contracts.ApprovalRuleRequest request)|ctors=IPCManagement.Api.Features.Approvals.Services.IApprovalRoutingService routingService|injected=
IPCManagement.Api.Features.Approvals.Controllers.ApprovalRulesController|DeleteRule|DELETE|api/approval-rules/{id}|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Approvals.Controllers.ApprovalRulesController.DeleteRuleAsync`0(System.String id)|ctors=IPCManagement.Api.Features.Approvals.Services.IApprovalRoutingService routingService|injected=
IPCManagement.Api.Features.Approvals.Controllers.ApprovalRulesController|UpdateRule|PUT|api/approval-rules/{id}|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Approvals.Controllers.ApprovalRulesController.UpdateRuleAsync`0(System.String id,IPCManagement.Api.Features.Approvals.Contracts.ApprovalRuleRequest request)|ctors=IPCManagement.Api.Features.Approvals.Services.IApprovalRoutingService routingService|injected=
IPCManagement.Api.Features.Approvals.Controllers.ApprovalsController|Execute|POST|api/approvals/{targetType}/{id}|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Approvals.Controllers.ApprovalsController.ExecuteAsync`0(System.String targetType,System.String id,IPCManagement.Api.Features.Approvals.Contracts.ApprovalRequest request)|ctors=IPCManagement.Api.Features.Approvals.Services.IApprovalInboxService approvalInboxService,IPCManagement.Api.Features.Approvals.Services.IApprovalWorkflowService approvalWorkflowService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Auth.Controllers.AuthController|Login|POST|api/Auth/login|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Auth.Controllers.AuthController.LoginAsync`0(IPCManagement.Api.Features.Auth.Contracts.LoginRequest request)|ctors=IPCManagement.Api.Features.Auth.Services.IAuthService authService,IPCManagement.Api.Security.ICurrentUserService currentUserService,IPCManagement.Api.Features.Auth.Services.ITokenService tokenService,Microsoft.Extensions.Logging.ILogger`1[IPCManagement.Api.Features.Auth.Controllers.AuthController] logger|injected=
IPCManagement.Api.Features.Auth.Controllers.AuthController|Logout|POST|api/Auth/logout|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Auth.Controllers.AuthController.LogoutAsync`0(IPCManagement.Api.Features.Auth.Contracts.RevokeTokenRequest request?)|ctors=IPCManagement.Api.Features.Auth.Services.IAuthService authService,IPCManagement.Api.Security.ICurrentUserService currentUserService,IPCManagement.Api.Features.Auth.Services.ITokenService tokenService,Microsoft.Extensions.Logging.ILogger`1[IPCManagement.Api.Features.Auth.Controllers.AuthController] logger|injected=
IPCManagement.Api.Features.Auth.Controllers.AuthController|Refresh|POST|api/Auth/refresh|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Auth.Controllers.AuthController.RefreshAsync`0(IPCManagement.Api.Features.Auth.Contracts.RefreshTokenRequest request?)|ctors=IPCManagement.Api.Features.Auth.Services.IAuthService authService,IPCManagement.Api.Security.ICurrentUserService currentUserService,IPCManagement.Api.Features.Auth.Services.ITokenService tokenService,Microsoft.Extensions.Logging.ILogger`1[IPCManagement.Api.Features.Auth.Controllers.AuthController] logger|injected=
IPCManagement.Api.Features.Auth.Controllers.AuthController|Revoke|POST|api/Auth/revoke|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Auth.Controllers.AuthController.RevokeAsync`0(IPCManagement.Api.Features.Auth.Contracts.RevokeTokenRequest request?)|ctors=IPCManagement.Api.Features.Auth.Services.IAuthService authService,IPCManagement.Api.Security.ICurrentUserService currentUserService,IPCManagement.Api.Features.Auth.Services.ITokenService tokenService,Microsoft.Extensions.Logging.ILogger`1[IPCManagement.Api.Features.Auth.Controllers.AuthController] logger|injected=
IPCManagement.Api.Features.Catalog.Controllers.DishBomController|AddBomLine|POST|api/Dishes/{id}/bom|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Catalog.Controllers.DishBomController.AddBomLineAsync`0(System.String id,IPCManagement.Api.Features.Catalog.Contracts.CreateDishBomLineRequest dto)|ctors=IPCManagement.Api.Features.Catalog.Services.IDishBomService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Catalog.Controllers.DishBomController|CloseBomLine|DELETE|api/Dishes/{id}/bom/{bomId}|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Catalog.Controllers.DishBomController.CloseBomLineAsync`0(System.String id,System.String bomId)|ctors=IPCManagement.Api.Features.Catalog.Services.IDishBomService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Catalog.Controllers.DishBomController|UpdateBomLine|PUT|api/Dishes/{id}/bom/{bomId}|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Catalog.Controllers.DishBomController.UpdateBomLineAsync`0(System.String id,System.String bomId,IPCManagement.Api.Features.Catalog.Contracts.UpdateDishBomLineRequest dto)|ctors=IPCManagement.Api.Features.Catalog.Services.IDishBomService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Catalog.Controllers.DishBomImportsController|CommitBomImport|POST|api/Dishes/bom-import/commit|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Catalog.Controllers.DishBomImportsController.CommitBomImportAsync`0(IPCManagement.Api.Features.Catalog.Contracts.BomImportCommitRequestDto request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Catalog.Services.IDishBomTemplateService templateService,IPCManagement.Api.Features.Catalog.Services.IDishBomImportService importService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Catalog.Controllers.DishBomImportsController|PreviewBomImport|POST|api/Dishes/bom-import/preview|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Catalog.Controllers.DishBomImportsController.PreviewBomImportAsync`0(IPCManagement.Api.Features.Catalog.Contracts.BomImportPreviewRequestDto request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Catalog.Services.IDishBomTemplateService templateService,IPCManagement.Api.Features.Catalog.Services.IDishBomImportService importService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Catalog.Controllers.DishesController|Create|POST|api/Dishes|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Catalog.Controllers.DishesController.CreateAsync`0(IPCManagement.Api.Features.Catalog.Contracts.CreateDishRequest dto)|ctors=IPCManagement.Api.Features.Catalog.Services.IDishCatalogService service|injected=
IPCManagement.Api.Features.Catalog.Controllers.DishesController|Delete|DELETE|api/Dishes/{id}|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Catalog.Controllers.DishesController.DeleteAsync`0(System.String id)|ctors=IPCManagement.Api.Features.Catalog.Services.IDishCatalogService service|injected=
IPCManagement.Api.Features.Catalog.Controllers.DishesController|Update|PUT|api/Dishes/{id}|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Catalog.Controllers.DishesController.UpdateAsync`0(System.String id,IPCManagement.Api.Features.Catalog.Contracts.UpdateDishRequest dto)|ctors=IPCManagement.Api.Features.Catalog.Services.IDishCatalogService service|injected=
IPCManagement.Api.Features.Catalog.Controllers.IngredientsController|Create|POST|api/Ingredients|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Catalog.Controllers.IngredientsController.CreateAsync`0(IPCManagement.Api.Features.Catalog.Contracts.CreateIngredientRequest dto)|ctors=IPCManagement.Api.Features.Catalog.Services.IIngredientService service|injected=
IPCManagement.Api.Features.Catalog.Controllers.IngredientsController|Delete|DELETE|api/Ingredients/{id}|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Catalog.Controllers.IngredientsController.DeleteAsync`0(System.String id)|ctors=IPCManagement.Api.Features.Catalog.Services.IIngredientService service|injected=
IPCManagement.Api.Features.Catalog.Controllers.IngredientsController|Update|PUT|api/Ingredients/{id}|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Catalog.Controllers.IngredientsController.UpdateAsync`0(System.String id,IPCManagement.Api.Features.Catalog.Contracts.UpdateIngredientRequest dto)|ctors=IPCManagement.Api.Features.Catalog.Services.IIngredientService service|injected=
IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController|AdjustOrderAfterLock|POST|api/coordination/orders/adjust|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController.AdjustOrderAfterLockAsync`0(IPCManagement.Api.Features.Coordination.Contracts.AdjustOrderAfterLockRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.IOrderPlanService planService,IPCManagement.Api.Features.Coordination.Services.IOrderAdjustmentService adjustmentService,IPCManagement.Api.Features.Coordination.Services.IOrderSignoffService signoffService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController|AdjustServings|PATCH|api/coordination/orders/{id}/servings|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController.AdjustServingsAsync`0(System.String id,IPCManagement.Api.Features.Coordination.Contracts.AdjustServingsRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.IOrderPlanService planService,IPCManagement.Api.Features.Coordination.Services.IOrderAdjustmentService adjustmentService,IPCManagement.Api.Features.Coordination.Services.IOrderSignoffService signoffService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController|ExportOrderReport|POST|api/coordination/orders/export|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController.ExportOrderReportAsync`0(IPCManagement.Api.Features.Coordination.Contracts.ExportOrderReportRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.IOrderPlanService planService,IPCManagement.Api.Features.Coordination.Services.IOrderAdjustmentService adjustmentService,IPCManagement.Api.Features.Coordination.Services.IOrderSignoffService signoffService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController|LockOrderPlan|POST|api/coordination/orders/lock|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController.LockOrderPlanAsync`0(IPCManagement.Api.Features.Coordination.Contracts.LockOrderPlanRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.IOrderPlanService planService,IPCManagement.Api.Features.Coordination.Services.IOrderAdjustmentService adjustmentService,IPCManagement.Api.Features.Coordination.Services.IOrderSignoffService signoffService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController|SignoffOrder|POST|api/coordination/orders/{id}/signoff|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController.SignoffOrderAsync`0(System.String id,IPCManagement.Api.Features.Coordination.Contracts.SignoffOrderRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.IOrderPlanService planService,IPCManagement.Api.Features.Coordination.Services.IOrderAdjustmentService adjustmentService,IPCManagement.Api.Features.Coordination.Services.IOrderSignoffService signoffService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController|SignoffOrderScope|POST|api/coordination/orders/signoff|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController.SignoffOrderScopeAsync`0(IPCManagement.Api.Features.Coordination.Contracts.CoordinationScopeActionRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.IOrderPlanService planService,IPCManagement.Api.Features.Coordination.Services.IOrderAdjustmentService adjustmentService,IPCManagement.Api.Features.Coordination.Services.IOrderSignoffService signoffService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController|UnlockOrderPlan|POST|api/coordination/orders/{id}/unlock|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController.UnlockOrderPlanAsync`0(System.String id)|ctors=IPCManagement.Api.Features.Coordination.Services.IOrderPlanService planService,IPCManagement.Api.Features.Coordination.Services.IOrderAdjustmentService adjustmentService,IPCManagement.Api.Features.Coordination.Services.IOrderSignoffService signoffService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController|UnlockOrderPlanScope|POST|api/coordination/orders/unlock|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController.UnlockOrderPlanScopeAsync`0(IPCManagement.Api.Features.Coordination.Contracts.CoordinationScopeActionRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.IOrderPlanService planService,IPCManagement.Api.Features.Coordination.Services.IOrderAdjustmentService adjustmentService,IPCManagement.Api.Features.Coordination.Services.IOrderSignoffService signoffService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController|UpdateForecastServings|PATCH|api/coordination/orders/{id}/forecast|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.CoordinationOrdersController.UpdateForecastServingsAsync`0(System.String id,IPCManagement.Api.Features.Coordination.Contracts.UpdateForecastServingsRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.IOrderPlanService planService,IPCManagement.Api.Features.Coordination.Services.IOrderAdjustmentService adjustmentService,IPCManagement.Api.Features.Coordination.Services.IOrderSignoffService signoffService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.CustomerContractsController|CreateCustomerContract|POST|api/coordination/customers/contract|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.CustomerContractsController.CreateCustomerContractAsync`0(IPCManagement.Api.Features.Coordination.Contracts.CreateCustomerContractRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.ICustomerContractService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.CustomerContractsController|UpdateCustomerContract|PUT|api/coordination/customers/{id}/contract|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.CustomerContractsController.UpdateCustomerContractAsync`0(System.String id,IPCManagement.Api.Features.Coordination.Contracts.UpdateCustomerContractRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.ICustomerContractService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.MealQuantityPlansController|UpsertQuickServings|POST|api/coordination/meal-quantity-plans/quick-servings|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.MealQuantityPlansController.UpsertQuickServingsAsync`0(IPCManagement.Api.Features.Coordination.Contracts.UpsertQuickServingsRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.IMealQuantityPlanService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.MenuSchedulesController|RollbackMenuVersion|POST|api/coordination/menu-versions/rollback|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.MenuSchedulesController.RollbackMenuVersionAsync`0(IPCManagement.Api.Features.Coordination.Contracts.RollbackMenuVersionRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.IMenuScheduleService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.MenuSchedulesController|UpdateMenuScheduleRules|PATCH|api/coordination/menu-schedules/{id}/rules|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.MenuSchedulesController.UpdateMenuScheduleRulesAsync`0(System.String id,IPCManagement.Api.Features.Coordination.Contracts.UpdateMenuScheduleRulesRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.IMenuScheduleService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.MenuSchedulesController|UpdateMenuScheduleVersion|PATCH|api/coordination/menu-schedules/{id}/version|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.MenuSchedulesController.UpdateMenuScheduleVersionAsync`0(System.String id,IPCManagement.Api.Features.Coordination.Contracts.UpdateMenuScheduleVersionRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.IMenuScheduleService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.PortionRulesController|CreatePortionRule|POST|api/coordination/portion-rules|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.PortionRulesController.CreatePortionRuleAsync`0(IPCManagement.Api.Features.Coordination.Contracts.CreatePortionRuleRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.IPortionRuleService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.PortionRulesController|ResolvePortionRule|POST|api/coordination/portion-rules/resolve|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.PortionRulesController.ResolvePortionRuleAsync`0(IPCManagement.Api.Features.Coordination.Contracts.ResolvePortionRuleRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.IPortionRuleService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Coordination.Controllers.PortionRulesController|UpdatePortionRule|PUT|api/coordination/portion-rules/{id}|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Coordination.Controllers.PortionRulesController.UpdatePortionRuleAsync`0(System.String id,IPCManagement.Api.Features.Coordination.Contracts.UpdatePortionRuleRequest request)|ctors=IPCManagement.Api.Features.Coordination.Services.IPortionRuleService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Inventory.Controllers.InventoryIssuesController|ConfirmReceipt|POST|api/inventory-issues/{id}/confirm-receipt|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Inventory.Controllers.InventoryIssuesController.ConfirmReceiptAsync`0(System.String id,IPCManagement.Api.Features.Inventory.Contracts.ConfirmInventoryIssueReceiptRequest dto)|ctors=IPCManagement.Api.Features.Inventory.Services.IInventoryIssueService inventoryIssueService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Inventory.Controllers.InventoryIssuesController|Create|POST|api/inventory-issues|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Inventory.Controllers.InventoryIssuesController.CreateAsync`0(IPCManagement.Api.Features.Inventory.Contracts.CreateInventoryIssueRequest dto)|ctors=IPCManagement.Api.Features.Inventory.Services.IInventoryIssueService inventoryIssueService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Inventory.Controllers.InventoryReceiptsController|Create|POST|api/inventory-receipts|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Inventory.Controllers.InventoryReceiptsController.CreateAsync`0(IPCManagement.Api.Features.Inventory.Contracts.CreateInventoryReceiptRequest dto)|ctors=IPCManagement.Api.Features.Inventory.Services.IInventoryReceiptService inventoryReceiptService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Inventory.Controllers.InventoryReceiptsController|CreateFromPurchase|POST|api/inventory-receipts/from-purchase|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Inventory.Controllers.InventoryReceiptsController.CreateFromPurchaseAsync`0(IPCManagement.Api.Features.Inventory.Contracts.CreateInventoryReceiptFromPurchaseRequest dto)|ctors=IPCManagement.Api.Features.Inventory.Services.IInventoryReceiptService inventoryReceiptService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Inventory.Controllers.InventoryReturnsController|ConfirmReceipt|POST|api/inventory-returns/{id}/confirm-receipt|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Inventory.Controllers.InventoryReturnsController.ConfirmReceiptAsync`0(System.String id,IPCManagement.Api.Features.Inventory.Contracts.ConfirmInventoryReturnReceiptRequest dto)|ctors=IPCManagement.Api.Features.Inventory.Services.IInventoryReturnService inventoryReturnService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Inventory.Controllers.InventoryReturnsController|Create|POST|api/inventory-returns|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Inventory.Controllers.InventoryReturnsController.CreateAsync`0(IPCManagement.Api.Features.Inventory.Contracts.CreateInventoryReturnRequest dto)|ctors=IPCManagement.Api.Features.Inventory.Services.IInventoryReturnService inventoryReturnService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Inventory.Controllers.InventoryReturnsController|CreateAllocationDisposition|POST|api/inventory-returns/allocation-dispositions|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Inventory.Controllers.InventoryReturnsController.CreateAllocationDispositionAsync`0(IPCManagement.Api.Features.Inventory.Contracts.CreateInventoryAllocationDispositionRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Inventory.Services.IInventoryReturnService inventoryReturnService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Inventory.Controllers.LegacyLineageDispositionsController|Apply|POST|api/legacy-lineage-dispositions/{id}/apply|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Inventory.Controllers.LegacyLineageDispositionsController.ApplyAsync`0(System.String id,IPCManagement.Api.Features.Inventory.Contracts.ApplyLegacyLineageDispositionRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Inventory.Services.ILegacyLineageDispositionService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Inventory.Controllers.LegacyLineageDispositionsController|Create|POST|api/legacy-lineage-dispositions|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Inventory.Controllers.LegacyLineageDispositionsController.CreateAsync`0(IPCManagement.Api.Features.Inventory.Contracts.CreateLegacyLineageDispositionRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Inventory.Services.ILegacyLineageDispositionService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Inventory.Controllers.LegacyLineageDispositionsController|Review|POST|api/legacy-lineage-dispositions/{id}/review|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Inventory.Controllers.LegacyLineageDispositionsController.ReviewAsync`0(System.String id,IPCManagement.Api.Features.Inventory.Contracts.ReviewLegacyLineageDispositionRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Inventory.Services.ILegacyLineageDispositionService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Inventory.Controllers.StocktakesController|Approve|POST|api/Stocktakes/{id}/approve|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[IPCManagement.Api.Helpers.ApiResponse`1[IPCManagement.Api.Features.Inventory.Contracts.StocktakeDto]]] IPCManagement.Api.Features.Inventory.Controllers.StocktakesController.ApproveAsync`0(System.String id)|ctors=IPCManagement.Api.Features.Inventory.Services.IStocktakeService stocktakeService|injected=
IPCManagement.Api.Features.Inventory.Controllers.StocktakesController|Create|POST|api/Stocktakes|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[IPCManagement.Api.Helpers.ApiResponse`1[IPCManagement.Api.Features.Inventory.Contracts.StocktakeDto]]] IPCManagement.Api.Features.Inventory.Controllers.StocktakesController.CreateAsync`0(IPCManagement.Api.Features.Inventory.Contracts.CreateStocktakeRequest dto)|ctors=IPCManagement.Api.Features.Inventory.Services.IStocktakeService stocktakeService|injected=
IPCManagement.Api.Features.Inventory.Controllers.StocktakesController|Reject|POST|api/Stocktakes/{id}/reject|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[IPCManagement.Api.Helpers.ApiResponse`1[IPCManagement.Api.Features.Inventory.Contracts.StocktakeDto]]] IPCManagement.Api.Features.Inventory.Controllers.StocktakesController.RejectAsync`0(System.String id,IPCManagement.Api.Features.Inventory.Controllers.RejectRequest dto)|ctors=IPCManagement.Api.Features.Inventory.Services.IStocktakeService stocktakeService|injected=
IPCManagement.Api.Features.Inventory.Controllers.StocktakesController|Submit|POST|api/Stocktakes/{id}/submit|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[IPCManagement.Api.Helpers.ApiResponse`1[IPCManagement.Api.Features.Inventory.Contracts.StocktakeDto]]] IPCManagement.Api.Features.Inventory.Controllers.StocktakesController.SubmitAsync`0(System.String id)|ctors=IPCManagement.Api.Features.Inventory.Services.IStocktakeService stocktakeService|injected=
IPCManagement.Api.Features.Inventory.Controllers.StocktakesController|UpdateActualQty|PUT|api/Stocktakes/{id}/actual-qty|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[IPCManagement.Api.Helpers.ApiResponse`1[IPCManagement.Api.Features.Inventory.Contracts.StocktakeDto]]] IPCManagement.Api.Features.Inventory.Controllers.StocktakesController.UpdateActualQtyAsync`0(System.String id,IPCManagement.Api.Features.Inventory.Contracts.UpdateStocktakeLinesRequest dto)|ctors=IPCManagement.Api.Features.Inventory.Services.IStocktakeService stocktakeService|injected=
IPCManagement.Api.Features.Inventory.Controllers.SupplementalMaterialRequestsController|Create|POST|api/supplemental-material-requests|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Inventory.Controllers.SupplementalMaterialRequestsController.CreateAsync`0(IPCManagement.Api.Features.Inventory.Contracts.CreateSupplementalMaterialRequest request)|ctors=IPCManagement.Api.Features.Inventory.Services.ISupplementalMaterialRequestService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Inventory.Controllers.SupplementalMaterialRequestsController|Fulfill|POST|api/supplemental-material-requests/{id}/fulfill|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Inventory.Controllers.SupplementalMaterialRequestsController.FulfillAsync`0(System.String id,IPCManagement.Api.Features.Inventory.Contracts.FulfillSupplementalMaterialRequest request)|ctors=IPCManagement.Api.Features.Inventory.Services.ISupplementalMaterialRequestService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Inventory.Controllers.SupplementalMaterialRequestsController|Reject|POST|api/supplemental-material-requests/{id}/reject|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Inventory.Controllers.SupplementalMaterialRequestsController.RejectAsync`0(System.String id,IPCManagement.Api.Features.Inventory.Contracts.RejectSupplementalMaterialRequest request)|ctors=IPCManagement.Api.Features.Inventory.Services.ISupplementalMaterialRequestService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Inventory.Controllers.SupplementalMaterialRequestsController|RouteToPurchasing|POST|api/supplemental-material-requests/{id}/route-to-purchasing|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Inventory.Controllers.SupplementalMaterialRequestsController.RouteToPurchasingAsync`0(System.String id,IPCManagement.Api.Features.Inventory.Contracts.RouteSupplementalMaterialRequestToPurchasing request)|ctors=IPCManagement.Api.Features.Inventory.Services.ISupplementalMaterialRequestService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Planning.Controllers.MaterialDemandController|Approve|POST|api/material-demand/{id}/approve|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Planning.Controllers.MaterialDemandController.ApproveAsync`0(System.String id,IPCManagement.Api.Features.Planning.Contracts.MaterialDemandApproveRequest request?,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Planning.Services.IMaterialDemandService materialDemandService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Planning.Controllers.MaterialDemandController|Generate|POST|api/material-demand/generate|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Planning.Controllers.MaterialDemandController.GenerateAsync`0(IPCManagement.Api.Features.Planning.Contracts.GenerateMaterialDemandRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Planning.Services.IMaterialDemandService materialDemandService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Planning.Controllers.ProductionPlansController|SendDailyToKitchen|POST|api/production-plans/daily/send-to-kitchen|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Planning.Controllers.ProductionPlansController.SendDailyToKitchenAsync`0(IPCManagement.Api.Features.Planning.Contracts.SendDailyProductionPlanRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Planning.Services.IProductionPlanService productionPlanService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Planning.Controllers.ServiceRunVarianceDeclarationsController|ApproveVarianceWaiver|POST|api/service-runs/{id}/variance/declarations/{declarationId}/waive|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Planning.Controllers.ServiceRunVarianceDeclarationsController.ApproveVarianceWaiverAsync`0(System.String id,System.String declarationId,IPCManagement.Api.Features.Planning.Contracts.ApproveServiceRunVarianceWaiverRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Planning.Services.IServiceRunService serviceRunService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Planning.Controllers.ServiceRunVarianceDeclarationsController|DeclareVariance|POST|api/service-runs/{id}/variance/declarations|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Planning.Controllers.ServiceRunVarianceDeclarationsController.DeclareVarianceAsync`0(System.String id,IPCManagement.Api.Features.Planning.Contracts.DeclareServiceRunVarianceRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Planning.Services.IServiceRunService serviceRunService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController|Close|POST|api/service-runs/{id}/close|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController.CloseAsync`0(System.String id,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Planning.Services.IServiceRunService serviceRunService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController|ConfirmService|POST|api/service-runs/{id}/service-confirmation|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController.ConfirmServiceAsync`0(System.String id,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Planning.Services.IServiceRunService serviceRunService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController|CreateAdjustment|POST|api/service-runs/{id}/adjustments|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController.CreateAdjustmentAsync`0(System.String id,IPCManagement.Api.Features.Planning.Contracts.CreateServiceRunAdjustmentRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Planning.Services.IServiceRunService serviceRunService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController|Open|POST|api/service-runs|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController.OpenAsync`0(IPCManagement.Api.Features.Planning.Contracts.OpenServiceRunRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Planning.Services.IServiceRunService serviceRunService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController|RecordActualServings|POST|api/service-runs/{id}/actual-servings|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController.RecordActualServingsAsync`0(System.String id,IPCManagement.Api.Features.Planning.Contracts.RecordActualServingsRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Planning.Services.IServiceRunService serviceRunService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController|ResolveServingVariance|POST|api/service-runs/{id}/serving-variance/resolve|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController.ResolveServingVarianceAsync`0(System.String id,IPCManagement.Api.Features.Planning.Contracts.ReasonRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Planning.Services.IServiceRunService serviceRunService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController|ResolveVariance|POST|api/service-runs/{id}/variance/resolve|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController.ResolveVarianceAsync`0(System.String id,IPCManagement.Api.Features.Planning.Contracts.ReasonRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Planning.Services.IServiceRunService serviceRunService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController|Start|POST|api/service-runs/{id}/start|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController.StartAsync`0(System.String id,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Planning.Services.IServiceRunService serviceRunService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController|WaiveServiceConfirmation|POST|api/service-runs/{id}/service-confirmation/waive|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Planning.Controllers.ServiceRunsController.WaiveServiceConfirmationAsync`0(System.String id,IPCManagement.Api.Features.Planning.Contracts.ReasonRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Planning.Services.IServiceRunService serviceRunService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Purchasing.Controllers.PurchaseOrdersController|Cancel|POST|api/purchase-orders/{id}/cancel|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Purchasing.Controllers.PurchaseOrdersController.CancelAsync`0(System.String id,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Purchasing.Services.IPurchaseOrderService purchaseOrderService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Purchasing.Controllers.PurchaseOrdersController|CreateFromRequest|POST|api/purchase-orders/from-request/{purchaseRequestId}|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Purchasing.Controllers.PurchaseOrdersController.CreateFromRequestAsync`0(System.String purchaseRequestId,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Purchasing.Services.IPurchaseOrderService purchaseOrderService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Purchasing.Controllers.PurchaseWorkflowController|ConfirmLineSupplier|POST|api/purchase-workflow/requests/{id}/lines/{lineId}/supplier-decision|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Purchasing.Controllers.PurchaseWorkflowController.ConfirmLineSupplierAsync`0(System.String id,System.String lineId,IPCManagement.Api.Features.Purchasing.Contracts.ConfirmPurchaseLineSupplierRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Purchasing.Services.IPurchaseWorkbenchService purchaseWorkbenchService,IPCManagement.Api.Features.Purchasing.Services.IPurchaseRequestGenerationService purchaseRequestGenerationService,IPCManagement.Api.Features.Purchasing.Services.IPurchaseSupplierDecisionService purchaseSupplierDecisionService,IPCManagement.Api.Features.Purchasing.Services.IPurchaseRequestSubmissionService purchaseRequestSubmissionService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Purchasing.Controllers.PurchaseWorkflowController|GenerateFromDemand|POST|api/purchase-workflow/from-demand|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Purchasing.Controllers.PurchaseWorkflowController.GenerateFromDemandAsync`0(IPCManagement.Api.Features.Purchasing.Contracts.GeneratePurchaseRequestFromDemandRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Purchasing.Services.IPurchaseWorkbenchService purchaseWorkbenchService,IPCManagement.Api.Features.Purchasing.Services.IPurchaseRequestGenerationService purchaseRequestGenerationService,IPCManagement.Api.Features.Purchasing.Services.IPurchaseSupplierDecisionService purchaseSupplierDecisionService,IPCManagement.Api.Features.Purchasing.Services.IPurchaseRequestSubmissionService purchaseRequestSubmissionService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Purchasing.Controllers.PurchaseWorkflowController|Submit|POST|api/purchase-workflow/requests/{id}/submit|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Purchasing.Controllers.PurchaseWorkflowController.SubmitAsync`0(System.String id,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Purchasing.Services.IPurchaseWorkbenchService purchaseWorkbenchService,IPCManagement.Api.Features.Purchasing.Services.IPurchaseRequestGenerationService purchaseRequestGenerationService,IPCManagement.Api.Features.Purchasing.Services.IPurchaseSupplierDecisionService purchaseSupplierDecisionService,IPCManagement.Api.Features.Purchasing.Services.IPurchaseRequestSubmissionService purchaseRequestSubmissionService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Purchasing.Controllers.SupplierQuotationsController|Create|POST|api/supplier-quotations|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Purchasing.Controllers.SupplierQuotationsController.CreateAsync`0(IPCManagement.Api.Features.Purchasing.Contracts.CreateSupplierQuotationRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Purchasing.Services.ISupplierQuotationService supplierQuotationService|injected=
IPCManagement.Api.Features.Purchasing.Controllers.SupplierQuotationsController|Deactivate|DELETE|api/supplier-quotations/{id}|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Purchasing.Controllers.SupplierQuotationsController.DeactivateAsync`0(System.String id,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Purchasing.Services.ISupplierQuotationService supplierQuotationService|injected=
IPCManagement.Api.Features.Purchasing.Controllers.SupplierQuotationsController|Update|PUT|api/supplier-quotations/{id}|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Purchasing.Controllers.SupplierQuotationsController.UpdateAsync`0(System.String id,IPCManagement.Api.Features.Purchasing.Contracts.UpdateSupplierQuotationRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Purchasing.Services.ISupplierQuotationService supplierQuotationService|injected=
IPCManagement.Api.Features.Purchasing.Controllers.WarehousePurchaseReceiptsController|AcceptQuality|POST|api/warehouse/purchase-orders/{purchaseOrderId}/receipts/{receiptId}/quality|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Purchasing.Controllers.WarehousePurchaseReceiptsController.AcceptQualityAsync`0(System.String receiptId,IPCManagement.Api.Features.Purchasing.Contracts.ReceiptQualityDecisionRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Purchasing.Services.IPurchaseReceivingService purchaseReceivingService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Purchasing.Controllers.WarehousePurchaseReceiptsController|CreateCorrection|POST|api/warehouse/purchase-orders/{purchaseOrderId}/receipts/{receiptId}/corrections|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Purchasing.Controllers.WarehousePurchaseReceiptsController.CreateCorrectionAsync`0(System.String receiptId,IPCManagement.Api.Features.Purchasing.Contracts.CreateReceiptCorrectionRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Purchasing.Services.IPurchaseReceivingService purchaseReceivingService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Purchasing.Controllers.WarehousePurchaseReceiptsController|Post|POST|api/warehouse/purchase-orders/{purchaseOrderId}/receipts/{receiptId}/post|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Purchasing.Controllers.WarehousePurchaseReceiptsController.PostAsync`0(System.String receiptId,IPCManagement.Api.Features.Purchasing.Contracts.ReceiptPostRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Purchasing.Services.IPurchaseReceivingService purchaseReceivingService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Purchasing.Controllers.WarehousePurchaseReceiptsController|Record|POST|api/warehouse/purchase-orders/{purchaseOrderId}/receipts|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Purchasing.Controllers.WarehousePurchaseReceiptsController.RecordAsync`0(System.String purchaseOrderId,IPCManagement.Api.Features.Purchasing.Contracts.RecordWarehousePurchaseReceiptRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Purchasing.Services.IPurchaseReceivingService purchaseReceivingService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Purchasing.Controllers.WarehousePurchaseReceiptsController|Rework|POST|api/warehouse/purchase-orders/{purchaseOrderId}/receipts/{receiptId}/rework|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Purchasing.Controllers.WarehousePurchaseReceiptsController.ReworkAsync`0(System.String receiptId,IPCManagement.Api.Features.Purchasing.Contracts.ReceiptReworkRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Purchasing.Services.IPurchaseReceivingService purchaseReceivingService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Purchasing.Controllers.WarehousePurchaseReceiptsController|Void|POST|api/warehouse/purchase-orders/{purchaseOrderId}/receipts/{receiptId}/void|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Purchasing.Controllers.WarehousePurchaseReceiptsController.VoidAsync`0(System.String receiptId,IPCManagement.Api.Features.Purchasing.Contracts.ReceiptVoidRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Purchasing.Services.IPurchaseReceivingService purchaseReceivingService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationActualsController|Disposition|PUT|api/reconciliation/lines/{lineId}/disposition|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationActualsController.Disposition`0(System.String lineId,IPCManagement.Api.Features.Reconciliation.Contracts.SetReconciliationDispositionRequest request,System.Threading.CancellationToken token)|ctors=IPCManagement.Api.Features.Reconciliation.Services.ReconciliationActualService service,IPCManagement.Api.Security.ICurrentUserService currentUser|injected=
IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationActualsController|Issued|PUT|api/reconciliation/lines/{lineId}/issued|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationActualsController.Issued`0(System.String lineId,IPCManagement.Api.Features.Reconciliation.Contracts.UpsertReconciliationActualRequest request,System.Threading.CancellationToken token)|ctors=IPCManagement.Api.Features.Reconciliation.Services.ReconciliationActualService service,IPCManagement.Api.Security.ICurrentUserService currentUser|injected=
IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationActualsController|Purchased|PUT|api/reconciliation/lines/{lineId}/purchased|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationActualsController.Purchased`0(System.String lineId,IPCManagement.Api.Features.Reconciliation.Contracts.UpsertReconciliationActualRequest request,System.Threading.CancellationToken token)|ctors=IPCManagement.Api.Features.Reconciliation.Services.ReconciliationActualService service,IPCManagement.Api.Security.ICurrentUserService currentUser|injected=
IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationBatchesController|CommitQuantityImport|POST|api/reconciliation/batches/quantity-import/commit|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationBatchesController.CommitQuantityImport`0(IPCManagement.Api.Features.Reconciliation.Contracts.CommitQuantityImportRequest request,System.Threading.CancellationToken token)|ctors=IPCManagement.Api.Features.Reconciliation.Services.ReconciliationBatchService service,IPCManagement.Api.Features.Reconciliation.Services.ReconciliationCompletionService completion,IPCManagement.Api.Features.Reconciliation.Services.ReconciliationQuantityImportService quantityImports,IPCManagement.Api.Security.ICurrentUserService currentUser|injected=
IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationBatchesController|Complete|POST|api/reconciliation/batches/{id}/complete|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationBatchesController.Complete`0(System.String id,IPCManagement.Api.Features.Reconciliation.Contracts.CompleteReconciliationBatchRequest request,System.Threading.CancellationToken token)|ctors=IPCManagement.Api.Features.Reconciliation.Services.ReconciliationBatchService service,IPCManagement.Api.Features.Reconciliation.Services.ReconciliationCompletionService completion,IPCManagement.Api.Features.Reconciliation.Services.ReconciliationQuantityImportService quantityImports,IPCManagement.Api.Security.ICurrentUserService currentUser|injected=
IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationBatchesController|Create|POST|api/reconciliation/batches|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationBatchesController.Create`0(IPCManagement.Api.Features.Reconciliation.Contracts.CreateReconciliationDraftRequest request,System.Threading.CancellationToken token)|ctors=IPCManagement.Api.Features.Reconciliation.Services.ReconciliationBatchService service,IPCManagement.Api.Features.Reconciliation.Services.ReconciliationCompletionService completion,IPCManagement.Api.Features.Reconciliation.Services.ReconciliationQuantityImportService quantityImports,IPCManagement.Api.Security.ICurrentUserService currentUser|injected=
IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationBatchesController|PreviewQuantityImport|POST|api/reconciliation/batches/quantity-import/preview|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationBatchesController.PreviewQuantityImport`0(IPCManagement.Api.Features.Reconciliation.Contracts.PreviewQuantityImportRequest request,System.Threading.CancellationToken token)|ctors=IPCManagement.Api.Features.Reconciliation.Services.ReconciliationBatchService service,IPCManagement.Api.Features.Reconciliation.Services.ReconciliationCompletionService completion,IPCManagement.Api.Features.Reconciliation.Services.ReconciliationQuantityImportService quantityImports,IPCManagement.Api.Security.ICurrentUserService currentUser|injected=
IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationBatchesController|Ready|POST|api/reconciliation/batches/{id}/ready|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationBatchesController.Ready`0(System.String id,IPCManagement.Api.Features.Reconciliation.Contracts.ReadyReconciliationBatchRequest request,System.Threading.CancellationToken token)|ctors=IPCManagement.Api.Features.Reconciliation.Services.ReconciliationBatchService service,IPCManagement.Api.Features.Reconciliation.Services.ReconciliationCompletionService completion,IPCManagement.Api.Features.Reconciliation.Services.ReconciliationQuantityImportService quantityImports,IPCManagement.Api.Security.ICurrentUserService currentUser|injected=
IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationBatchesController|TransferToWarehouse|POST|api/reconciliation/batches/{id}/transfer-to-warehouse|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationBatchesController.TransferToWarehouse`0(System.String id,IPCManagement.Api.Features.Reconciliation.Contracts.TransferReconciliationBatchRequest request,System.Threading.CancellationToken token)|ctors=IPCManagement.Api.Features.Reconciliation.Services.ReconciliationBatchService service,IPCManagement.Api.Features.Reconciliation.Services.ReconciliationCompletionService completion,IPCManagement.Api.Features.Reconciliation.Services.ReconciliationQuantityImportService quantityImports,IPCManagement.Api.Security.ICurrentUserService currentUser|injected=
IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationConfigurationController|InitializeSystemDefault|POST|api/reconciliation/configuration/system-default/initialize|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reconciliation.Controllers.ReconciliationConfigurationController.InitializeSystemDefault`0(System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Reconciliation.Services.ReconciliationToleranceInitializer initializer,IPCManagement.Api.Security.ICurrentUserService currentUser|injected=
IPCManagement.Api.Features.Reports.Controllers.DataQualityDispositionsController|Apply|POST|api/data-quality-dispositions/{id}/apply|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reports.Controllers.DataQualityDispositionsController.ApplyAsync`0(System.String id,IPCManagement.Api.Features.Reports.Contracts.ApplyDataQualityDispositionRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Reports.Services.IDataQualityDispositionService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Reports.Controllers.DataQualityDispositionsController|Create|POST|api/data-quality-dispositions|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reports.Controllers.DataQualityDispositionsController.CreateAsync`0(IPCManagement.Api.Features.Reports.Contracts.CreateDataQualityDispositionRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Reports.Services.IDataQualityDispositionService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Reports.Controllers.DataQualityDispositionsController|Review|POST|api/data-quality-dispositions/{id}/review|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reports.Controllers.DataQualityDispositionsController.ReviewAsync`0(System.String id,IPCManagement.Api.Features.Reports.Contracts.ReviewDataQualityDispositionRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Reports.Services.IDataQualityDispositionService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Reports.Controllers.StockSnapshotReportsController|GenerateStockSnapshots|POST|api/workflow-reports/stock-snapshots/generate|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reports.Controllers.StockSnapshotReportsController.GenerateStockSnapshotsAsync`0(IPCManagement.Api.Shared.Contracts.WorkflowReportQueryDto query)|ctors=IPCManagement.Api.Features.Reports.Services.IStockSnapshotReportService reportService|injected=
IPCManagement.Api.Features.Reports.Controllers.UnitNormalizationReviewsController|Decide|POST|api/unit-normalization-reviews/{reviewId}/decision|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reports.Controllers.UnitNormalizationReviewsController.DecideAsync`0(System.String reviewId,IPCManagement.Api.Features.Reports.Contracts.UnitNormalizationReviewDecisionRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.Reports.Services.IUnitNormalizationReviewService service,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Reports.Controllers.WorkflowReportsController|CleanupDataQuality|POST|api/workflow-reports/data-quality/cleanup|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reports.Controllers.WorkflowReportsController.CleanupDataQualityAsync`0(IPCManagement.Api.Features.Reports.Contracts.DataQualityCleanupRequest request)|ctors=IPCManagement.Api.Features.Reports.Services.IDataQualityReportService dataQualityReportService,IPCManagement.Api.Features.Reports.Services.IDataQualityCommandService dataQualityCommandService,IPCManagement.Api.Features.Reports.Services.IOperationalKpiReportService operationalKpiReportService,IPCManagement.Api.Features.Reports.Services.IWorkflowReportAggregateCache aggregateCache,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.Reports.Controllers.WorkflowReportsController|UpdateDataQualityIssueRemediation|POST|api/workflow-reports/data-quality/issues/remediation|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.Reports.Controllers.WorkflowReportsController.UpdateDataQualityIssueRemediationAsync`0(IPCManagement.Api.Features.Reports.Contracts.DataQualityIssueRemediationRequest request)|ctors=IPCManagement.Api.Features.Reports.Services.IDataQualityReportService dataQualityReportService,IPCManagement.Api.Features.Reports.Services.IDataQualityCommandService dataQualityCommandService,IPCManagement.Api.Features.Reports.Services.IOperationalKpiReportService operationalKpiReportService,IPCManagement.Api.Features.Reports.Services.IWorkflowReportAggregateCache aggregateCache,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.SampleData.Controllers.SampleDataController|ApplyPurchaseHistory|POST|api/sample-data/purchase-history/apply|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SampleData.Controllers.SampleDataController.ApplyPurchaseHistoryAsync`0(IPCManagement.Api.Features.SampleData.Contracts.PurchaseHistoryApplyRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SampleData.Services.ISampleBomImportService sampleDataImportService,IPCManagement.Api.Features.SampleData.Services.IPurchaseHistoryReconciliationService purchaseHistoryReconciliationService,Microsoft.Extensions.Hosting.IHostEnvironment environment|injected=
IPCManagement.Api.Features.SampleData.Controllers.SampleDataController|Import|POST|api/sample-data/import|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SampleData.Controllers.SampleDataController.ImportAsync`0(IPCManagement.Api.Features.SampleData.Contracts.SampleDataImportRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SampleData.Services.ISampleBomImportService sampleDataImportService,IPCManagement.Api.Features.SampleData.Services.IPurchaseHistoryReconciliationService purchaseHistoryReconciliationService,Microsoft.Extensions.Hosting.IHostEnvironment environment|injected=
IPCManagement.Api.Features.SampleData.Controllers.SampleDataController|PreviewPurchaseHistory|POST|api/sample-data/purchase-history/preview|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SampleData.Controllers.SampleDataController.PreviewPurchaseHistoryAsync`0(IPCManagement.Api.Features.SampleData.Contracts.PurchaseHistoryPreviewRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SampleData.Services.ISampleBomImportService sampleDataImportService,IPCManagement.Api.Features.SampleData.Services.IPurchaseHistoryReconciliationService purchaseHistoryReconciliationService,Microsoft.Extensions.Hosting.IHostEnvironment environment|injected=
IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuBatchImportsController|Commit|POST|api/coordination/weekly-menu/import/commit-batch|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuBatchImportsController.CommitAsync`0(System.Collections.Generic.List`1[Microsoft.AspNetCore.Http.IFormFile] files,System.Collections.Generic.List`1[System.String] customerIds,System.Collections.Generic.List`1[System.String] weekStartDates,System.Collections.Generic.List`1[System.Decimal] priceTierAmounts,System.Collections.Generic.List`1[System.String] previewTokens,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportService importService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController|BreakGlassExecuteMenuAmendment|POST|api/coordination/weekly-menu/amendments/{amendmentId}/break-glass-execute|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController.BreakGlassExecuteMenuAmendmentAsync`0(System.String amendmentId,IPCManagement.Api.Features.SampleData.Contracts.BreakGlassMenuAmendmentRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuQueryService queryService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuTemplateService templateService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportService importService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportHistoryService historyService,IPCManagement.Api.Features.SampleData.Services.ICustomerImportMappingService mappingService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuBulkEditService bulkEditService,IPCManagement.Api.Features.SampleData.Services.IMenuAmendmentService menuAmendmentService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController|BulkUpdateWeeklyMenu|PUT|api/coordination/weekly-menu/bulk-update|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController.BulkUpdateWeeklyMenuAsync`0(IPCManagement.Api.Features.Coordination.Contracts.BulkUpdateWeeklyMenuRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuQueryService queryService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuTemplateService templateService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportService importService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportHistoryService historyService,IPCManagement.Api.Features.SampleData.Services.ICustomerImportMappingService mappingService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuBulkEditService bulkEditService,IPCManagement.Api.Features.SampleData.Services.IMenuAmendmentService menuAmendmentService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController|CommitWeeklyMenuImport|POST|api/coordination/weekly-menu/import/commit|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController.CommitWeeklyMenuImportAsync`0(Microsoft.AspNetCore.Http.IFormFile file,System.String customerId,System.String weekStartDate?,System.Nullable`1[System.Decimal] priceTierAmount?,System.String previewToken?,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuQueryService queryService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuTemplateService templateService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportService importService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportHistoryService historyService,IPCManagement.Api.Features.SampleData.Services.ICustomerImportMappingService mappingService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuBulkEditService bulkEditService,IPCManagement.Api.Features.SampleData.Services.IMenuAmendmentService menuAmendmentService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController|CreateMenuAmendment|POST|api/coordination/weekly-menu/amendments|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController.CreateMenuAmendmentAsync`0(IPCManagement.Api.Features.SampleData.Contracts.CreateMenuAmendmentRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuQueryService queryService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuTemplateService templateService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportService importService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportHistoryService historyService,IPCManagement.Api.Features.SampleData.Services.ICustomerImportMappingService mappingService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuBulkEditService bulkEditService,IPCManagement.Api.Features.SampleData.Services.IMenuAmendmentService menuAmendmentService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController|ExecuteMenuAmendment|POST|api/coordination/weekly-menu/amendments/{amendmentId}/execute|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController.ExecuteMenuAmendmentAsync`0(System.String amendmentId,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuQueryService queryService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuTemplateService templateService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportService importService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportHistoryService historyService,IPCManagement.Api.Features.SampleData.Services.ICustomerImportMappingService mappingService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuBulkEditService bulkEditService,IPCManagement.Api.Features.SampleData.Services.IMenuAmendmentService menuAmendmentService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController|ExecuteMenuAmendmentDecision|POST|api/coordination/weekly-menu/amendments/decisions/{decisionItemId}/commands|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController.ExecuteMenuAmendmentDecisionAsync`0(System.String decisionItemId,IPCManagement.Api.Features.SampleData.Contracts.MenuAmendmentDecisionCommandRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuQueryService queryService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuTemplateService templateService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportService importService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportHistoryService historyService,IPCManagement.Api.Features.SampleData.Services.ICustomerImportMappingService mappingService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuBulkEditService bulkEditService,IPCManagement.Api.Features.SampleData.Services.IMenuAmendmentService menuAmendmentService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController|ImportWeeklyMenu|POST|api/coordination/weekly-menu/import|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController.ImportWeeklyMenuAsync`0(Microsoft.AspNetCore.Http.IFormFile file,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuQueryService queryService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuTemplateService templateService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportService importService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportHistoryService historyService,IPCManagement.Api.Features.SampleData.Services.ICustomerImportMappingService mappingService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuBulkEditService bulkEditService,IPCManagement.Api.Features.SampleData.Services.IMenuAmendmentService menuAmendmentService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController|PreviewWeeklyMenuImport|POST|api/coordination/weekly-menu/import/preview|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController.PreviewWeeklyMenuImportAsync`0(Microsoft.AspNetCore.Http.IFormFile file,System.String customerId,System.String weekStartDate?,System.Nullable`1[System.Decimal] priceTierAmount?,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuQueryService queryService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuTemplateService templateService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportService importService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportHistoryService historyService,IPCManagement.Api.Features.SampleData.Services.ICustomerImportMappingService mappingService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuBulkEditService bulkEditService,IPCManagement.Api.Features.SampleData.Services.IMenuAmendmentService menuAmendmentService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController|RemediateMenuAmendmentDecisionFan|POST|api/coordination/weekly-menu/amendments/reconciliation-cases/{reconciliationCaseId}/decision-fan-remediations|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController.RemediateMenuAmendmentDecisionFanAsync`0(System.String reconciliationCaseId,IPCManagement.Api.Features.SampleData.Contracts.RemediateMenuAmendmentDecisionFanRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuQueryService queryService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuTemplateService templateService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportService importService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportHistoryService historyService,IPCManagement.Api.Features.SampleData.Services.ICustomerImportMappingService mappingService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuBulkEditService bulkEditService,IPCManagement.Api.Features.SampleData.Services.IMenuAmendmentService menuAmendmentService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController|ReviewMenuAmendment|POST|api/coordination/weekly-menu/amendments/{amendmentId}/review|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController.ReviewMenuAmendmentAsync`0(System.String amendmentId,IPCManagement.Api.Features.SampleData.Contracts.ReviewMenuAmendmentRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuQueryService queryService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuTemplateService templateService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportService importService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportHistoryService historyService,IPCManagement.Api.Features.SampleData.Services.ICustomerImportMappingService mappingService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuBulkEditService bulkEditService,IPCManagement.Api.Features.SampleData.Services.IMenuAmendmentService menuAmendmentService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController|RollbackWeeklyMenuImport|POST|api/coordination/weekly-menu/import/{menuVersionId}/rollback|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController.RollbackWeeklyMenuImportAsync`0(System.String menuVersionId,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuQueryService queryService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuTemplateService templateService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportService importService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportHistoryService historyService,IPCManagement.Api.Features.SampleData.Services.ICustomerImportMappingService mappingService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuBulkEditService bulkEditService,IPCManagement.Api.Features.SampleData.Services.IMenuAmendmentService menuAmendmentService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController|SaveCustomerImportMapping|PUT|api/coordination/customers/{customerId}/import-mapping|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SampleData.Controllers.WeeklyMenuImportsController.SaveCustomerImportMappingAsync`0(System.String customerId,IPCManagement.Api.Features.SampleData.Contracts.SaveCustomerImportMappingRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuQueryService queryService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuTemplateService templateService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportService importService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuImportHistoryService historyService,IPCManagement.Api.Features.SampleData.Services.ICustomerImportMappingService mappingService,IPCManagement.Api.Features.SampleData.Services.IWeeklyMenuBulkEditService bulkEditService,IPCManagement.Api.Features.SampleData.Services.IMenuAmendmentService menuAmendmentService,IPCManagement.Api.Security.ICurrentUserService currentUserService|injected=
IPCManagement.Api.Features.SystemOperation.Controllers.SystemOperationModeController|Change|PUT|api/system-operation-mode|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SystemOperation.Controllers.SystemOperationModeController.ChangeAsync`0(IPCManagement.Api.Features.SystemOperation.Contracts.ChangeSystemOperationModeRequest request,System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SystemOperation.Services.SystemOperationModeService service,IPCManagement.Api.Features.SystemOperation.Services.SystemOperationModeInitializer initializer,IPCManagement.Api.Security.ICurrentUserService currentUser|injected=
IPCManagement.Api.Features.SystemOperation.Controllers.SystemOperationModeController|Initialize|POST|api/system-operation-mode/initialize|System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] IPCManagement.Api.Features.SystemOperation.Controllers.SystemOperationModeController.InitializeAsync`0(System.Threading.CancellationToken cancellationToken)|ctors=IPCManagement.Api.Features.SystemOperation.Services.SystemOperationModeService service,IPCManagement.Api.Features.SystemOperation.Services.SystemOperationModeInitializer initializer,IPCManagement.Api.Security.ICurrentUserService currentUser|injected=
""".Split('\n').Select(x => x.TrimEnd('\r')).ToArray();

    private sealed record MutationActionContract(string ControllerFullName, string ActionName, string[] HttpMethods, string EffectiveRoute, string MethodSignature, string[][] PublicConstructorContracts, string[] ActionInjectedContracts);
    private sealed record DescriptorContract(string ServiceType, string Shape, string Contract);
}
